Repository refugies-info/karfur, pull requests merged in 2022-06, with the labels that each got.

#1218 various improvements
  client/src/containers/Backend/Admin/AdminContenu/ContentDetailsModal/ContentDetailsModal.tsx
  client/src/containers/Backend/Admin/sharedComponents/StatusRow.tsx
  client/src/containers/Backend/UserTranslation/__tests__/UserTranslation.component.test.tsx
  client/src/containers/Translation/Translation.js
  client/src/hooks/useRouterLocale.ts
  server/src/workflows/dispositif/updateDispositifAdminComments/updateDispositifAdminComments.ts
Labels: enhancement

#1217 update map
  client/src/assets/assetsOnServer.ts
Labels: enhancement

#1213 add departments
  server/src/controllers/miscellaneous/airtable.js
  server/src/controllers/miscellaneousController.js
  server/src/libs/__tests__/getDispositifDepartments.test.ts
  server/src/libs/getDispositifDepartments.ts
  server/src/modules/dispositif/__tests__/dispositif.service.test.ts
  server/src/modules/dispositif/dispositif.service.ts
  server/src/workflows/dispositif/addDispositif/addDispositif.ts
  server/src/workflows/dispositif/updateDispositifStatus/updateDispositifStatus.test.ts
  server/src/workflows/dispositif/updateDispositifStatus/updateDispositifStatus.ts
  server/src/workflows/miscellaneaous/updateAirtableContenus.ts
  server/src/workflows/translation/validateTranslations/validateTranslations.test.ts
  server/src/workflows/translation/validateTranslations/validateTranslations.ts
Labels: enhancement

#1219 [STG-BACK] Release
  client/src/assets/assetsOnServer.ts
  client/src/containers/Backend/Admin/AdminContenu/ContentDetailsModal/ContentDetailsModal.tsx
  client/src/containers/Backend/Admin/sharedComponents/StatusRow.tsx
  client/src/containers/Backend/UserTranslation/__tests__/UserTranslation.component.test.tsx
  client/src/containers/Translation/Translation.js
  client/src/hooks/useRouterLocale.ts
  server/src/controllers/miscellaneous/airtable.js
  server/src/controllers/miscellaneousController.js
  server/src/libs/__tests__/getDispositifDepartments.test.ts
  server/src/libs/getDispositifDepartments.ts
  server/src/modules/dispositif/__tests__/dispositif.service.test.ts
  server/src/modules/dispositif/dispositif.service.ts
  server/src/workflows/dispositif/addDispositif/addDispositif.ts
  server/src/workflows/dispositif/updateDispositifAdminComments/updateDispositifAdminComments.ts
  server/src/workflows/dispositif/updateDispositifStatus/updateDispositifStatus.test.ts
  server/src/workflows/dispositif/updateDispositifStatus/updateDispositifStatus.ts
  server/src/workflows/miscellaneaous/updateAirtableContenus.ts
  server/src/workflows/translation/validateTranslations/validateTranslations.test.ts
  server/src/workflows/translation/validateTranslations/validateTranslations.ts
Labels: release

#1220 [STG-FRONT] Release
  client/src/assets/assetsOnServer.ts
  client/src/containers/Backend/Admin/AdminContenu/ContentDetailsModal/ContentDetailsModal.tsx
  client/src/containers/Backend/Admin/sharedComponents/StatusRow.tsx
  client/src/containers/Backend/UserTranslation/__tests__/UserTranslation.component.test.tsx
  client/src/containers/Translation/Translation.js
  client/src/hooks/useRouterLocale.ts
  server/src/controllers/miscellaneous/airtable.js
  server/src/controllers/miscellaneousController.js
  server/src/libs/__tests__/getDispositifDepartments.test.ts
  server/src/libs/getDispositifDepartments.ts
  server/src/modules/dispositif/__tests__/dispositif.service.test.ts
  server/src/modules/dispositif/dispositif.service.ts
  server/src/workflows/dispositif/addDispositif/addDispositif.ts
  server/src/workflows/dispositif/updateDispositifAdminComments/updateDispositifAdminComments.ts
  server/src/workflows/dispositif/updateDispositifStatus/updateDispositifStatus.test.ts
  server/src/workflows/dispositif/updateDispositifStatus/updateDispositifStatus.ts
  server/src/workflows/miscellaneaous/updateAirtableContenus.ts
  server/src/workflows/translation/validateTranslations/validateTranslations.test.ts
  server/src/workflows/translation/validateTranslations/validateTranslations.ts
Labels: release

#1221 update dependencies and tests
  client/package-lock.json
  client/package.json
  client/src/components/Pages/advanced-search/MobileAdvancedSearch/SearchResultsDisplayedOnMobile/LoadingFicheOnMobile.tsx
  client/src/components/Pages/dispositif/SideTrad/ExpertSideTrad.js
  client/src/components/Pages/dispositif/SideTrad/SideTrad.js
  client/src/containers/Backend/Admin/AdminContenu/components/LoadingAdminContenu.tsx
  client/src/containers/Backend/Admin/AdminStructures/components/LoadingAdminStructures.tsx
  client/src/containers/Backend/Admin/AdminUsers/ components/LoadingAdminUsers.tsx
  client/src/containers/Backend/Admin/Needs/LoadingNeeds.tsx
  client/src/containers/Backend/UserContributions/__tests__/__snapshots__/UserContributions.component.test.tsx.snap
  client/src/containers/Backend/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  client/src/containers/Backend/UserNotifications/__tests__/__snapshots__/UserNotifications.test.tsx.snap
  client/src/containers/Backend/UserProfile/__test__/__snapshots__/UserProfile.component.test.tsx.snap
  client/src/containers/Backend/UserProfile/components/UserProfileLoading.tsx
  client/src/containers/Backend/UserStructure/__tests__/__snapshots__/UserStructure.test.tsx.snap
  client/src/containers/Backend/UserStructure/components/AddMemberModal.tsx
  client/src/containers/Backend/UserStructure/components/UserStructureLoading.tsx
  client/src/containers/Backend/UserTranslation/__tests__/__snapshots__/UserTranslation.component.test.tsx.snap
  client/src/containers/Backend/UserTranslation/components/LoadingDispositifsWithTranslationsStatus.tsx
  client/src/containers/Backend/UserTranslation/components/TranslationNeedsModal.tsx
  client/src/scss/index.scss
Labels: dependencies

#1222 [STG-FRONT] Release
  client/package-lock.json
  client/package.json
  client/src/components/Pages/advanced-search/MobileAdvancedSearch/SearchResultsDisplayedOnMobile/LoadingFicheOnMobile.tsx
  client/src/components/Pages/dispositif/SideTrad/ExpertSideTrad.js
  client/src/components/Pages/dispositif/SideTrad/SideTrad.js
  client/src/containers/Backend/Admin/AdminContenu/components/LoadingAdminContenu.tsx
  client/src/containers/Backend/Admin/AdminStructures/components/LoadingAdminStructures.tsx
  client/src/containers/Backend/Admin/AdminUsers/ components/LoadingAdminUsers.tsx
  client/src/containers/Backend/Admin/Needs/LoadingNeeds.tsx
  client/src/containers/Backend/UserContributions/__tests__/__snapshots__/UserContributions.component.test.tsx.snap
  client/src/containers/Backend/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  client/src/containers/Backend/UserNotifications/__tests__/__snapshots__/UserNotifications.test.tsx.snap
  client/src/containers/Backend/UserProfile/__test__/__snapshots__/UserProfile.component.test.tsx.snap
  client/src/containers/Backend/UserProfile/components/UserProfileLoading.tsx
  client/src/containers/Backend/UserStructure/__tests__/__snapshots__/UserStructure.test.tsx.snap
  client/src/containers/Backend/UserStructure/components/AddMemberModal.tsx
  client/src/containers/Backend/UserStructure/components/UserStructureLoading.tsx
  client/src/containers/Backend/UserTranslation/__tests__/__snapshots__/UserTranslation.component.test.tsx.snap
  client/src/containers/Backend/UserTranslation/components/LoadingDispositifsWithTranslationsStatus.tsx
  client/src/containers/Backend/UserTranslation/components/TranslationNeedsModal.tsx
  client/src/scss/index.scss
Labels: release

#1223 fix server paths
  server/src/libs/getDispositifDepartments.ts
  server/src/workflows/miscellaneaous/updateAirtableContenus.ts
  server/src/workflows/structure/getAllStructures/getAllStructures.test.ts
Labels: bug

#1224 [STG-BACK] Release
  client/package-lock.json
  client/package.json
  client/src/components/Pages/advanced-search/MobileAdvancedSearch/SearchResultsDisplayedOnMobile/LoadingFicheOnMobile.tsx
  client/src/components/Pages/dispositif/SideTrad/ExpertSideTrad.js
  client/src/components/Pages/dispositif/SideTrad/SideTrad.js
  client/src/containers/Backend/Admin/AdminContenu/components/LoadingAdminContenu.tsx
  client/src/containers/Backend/Admin/AdminStructures/components/LoadingAdminStructures.tsx
  client/src/containers/Backend/Admin/AdminUsers/ components/LoadingAdminUsers.tsx
  client/src/containers/Backend/Admin/Needs/LoadingNeeds.tsx
  client/src/containers/Backend/UserContributions/__tests__/__snapshots__/UserContributions.component.test.tsx.snap
  client/src/containers/Backend/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  client/src/containers/Backend/UserNotifications/__tests__/__snapshots__/UserNotifications.test.tsx.snap
  client/src/containers/Backend/UserProfile/__test__/__snapshots__/UserProfile.component.test.tsx.snap
  client/src/containers/Backend/UserProfile/components/UserProfileLoading.tsx
  client/src/containers/Backend/UserStructure/__tests__/__snapshots__/UserStructure.test.tsx.snap
  client/src/containers/Backend/UserStructure/components/AddMemberModal.tsx
  client/src/containers/Backend/UserStructure/components/UserStructureLoading.tsx
  client/src/containers/Backend/UserTranslation/__tests__/__snapshots__/UserTranslation.component.test.tsx.snap
  client/src/containers/Backend/UserTranslation/components/LoadingDispositifsWithTranslationsStatus.tsx
  client/src/containers/Backend/UserTranslation/components/TranslationNeedsModal.tsx
  client/src/scss/index.scss
  server/src/libs/getDispositifDepartments.ts
  server/src/workflows/miscellaneaous/updateAirtableContenus.ts
  server/src/workflows/structure/getAllStructures/getAllStructures.test.ts
Labels: release

#1214 Progress lang color
  client/src/components/Modals/LanguageModal/LanguageModal.module.scss
  client/src/components/Modals/LanguageModal/LanguageModal.tsx
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  client/src/containers/Backend/Admin/AdminUsers/AdminUsers.tsx
  client/src/scss/_variables.scss
Labels: enhancement

#1229 various fixes
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/components/Modals/LanguageModal/LanguageModal.tsx
  client/src/components/Pages/advanced-search/SearchResults/SearchResults.module.scss
  client/src/components/Pages/advanced-search/SearchResults/ThemeResults.tsx
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  client/src/containers/Backend/Admin/AdminStructures/AdminStructures.tsx
  client/src/containers/Backend/Admin/AdminUsers/AdminUsers.tsx
  client/src/containers/Backend/Admin/Logs/functions.tsx
  client/src/containers/Backend/Admin/Needs/Needs.tsx
  client/src/containers/Backend/Admin/Widgets/EditWidgetModal/EditWidgetModal.tsx
  client/src/containers/Backend/Admin/Widgets/Widgets.module.scss
  client/src/containers/Backend/Admin/Widgets/Widgets.tsx
  client/src/containers/Backend/Admin/sharedComponents/StyledAdmin.ts
  client/src/scss/_colors.scss
  client/src/scss/_variables.scss
  client/src/types/interface.d.ts
  server/src/modules/logs/logs.repository.ts
Labels: bug

#1230 [STG-FRONT] Release
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/components/Modals/LanguageModal/LanguageModal.tsx
  client/src/components/Pages/advanced-search/SearchResults/SearchResults.module.scss
  client/src/components/Pages/advanced-search/SearchResults/ThemeResults.tsx
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  client/src/containers/Backend/Admin/AdminStructures/AdminStructures.tsx
  client/src/containers/Backend/Admin/AdminUsers/AdminUsers.tsx
  client/src/containers/Backend/Admin/Logs/functions.tsx
  client/src/containers/Backend/Admin/Needs/Needs.tsx
  client/src/containers/Backend/Admin/Widgets/EditWidgetModal/EditWidgetModal.tsx
  client/src/containers/Backend/Admin/Widgets/Widgets.module.scss
  client/src/containers/Backend/Admin/Widgets/Widgets.tsx
  client/src/containers/Backend/Admin/sharedComponents/StyledAdmin.ts
  client/src/scss/_colors.scss
  client/src/scss/_variables.scss
  client/src/types/interface.d.ts
  server/src/modules/logs/logs.repository.ts
Labels: release

#1232 fix API paths
  client/src/utils/API.ts
Labels: bug

#1233 [STG-FRONT] Release
  client/src/utils/API.ts
Labels: release

#1237 [STG-BACK] Release
  client/src/utils/API.ts
  server/src/modules/dispositif/__tests__/dispositif.adapter.test.ts
  server/src/modules/dispositif/dispositif.adapter.ts
Labels: release

#1240 [STG-FRONT]
  .prettierrc
  client/package-lock.json
  client/src/components/Pages/comment-contribuer/DispositifCard.tsx
  client/src/components/Pages/comment-contribuer/Langue.tsx
  client/src/components/Pages/login/Footer.tsx
  client/src/pages/comment-contribuer.tsx
  client/src/pages/login.tsx
  client/src/pages/register.tsx
  package-lock.json
  server/package-lock.json
  server/src/modules/dispositif/__tests__/dispositif.adapter.test.ts
  server/src/modules/dispositif/dispositif.adapter.ts
Labels: release

#1241 [STG-FRONT] Release
  client/package-lock.json
  server/package-lock.json
Labels: release

#1242 [STG-BACK] Release
  .prettierrc
  client/src/components/Pages/comment-contribuer/DispositifCard.tsx
  client/src/components/Pages/comment-contribuer/Langue.tsx
  client/src/components/Pages/login/Footer.tsx
  client/src/pages/comment-contribuer.tsx
  client/src/pages/login.tsx
  client/src/pages/register.tsx
  package-lock.json
Labels: release
