Repository refugies-info/karfur, pull requests merged in 2022-05, with the labels that each got.

#1170 bugfixes
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.module.scss
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.tsx
  client/src/components/Layout/Layout.tsx
  client/src/containers/Backend/Admin/Admin.tsx
  client/src/containers/Backend/Dashboard/Dashboard.tsx
  client/src/containers/Backend/UserContributions/UserContributions.tsx
  client/src/containers/Backend/UserFavorites/UserFavorites.tsx
  client/src/containers/Backend/UserNotifications/UserNotifications.tsx
  client/src/containers/Backend/UserProfile/UserProfile.tsx
  client/src/containers/Backend/UserStructure/UserStructure.component.tsx
  client/src/containers/Backend/UserStructure/UserStructureAdmin.component.tsx
  client/src/containers/Backend/UserTranslation/UserTranslation.tsx
  client/src/containers/Backend/routes.ts
  client/src/containers/Translation/Translation.js
  client/src/pages/backend/[...backend].tsx
  server/src/controllers/account/lib.js
Labels: bug

#1172 [STG-BACK] Release
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.module.scss
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.tsx
  client/src/components/Frontend/Dispositif/LeftSideDispositif/LeftSideDispositif.module.scss
  client/src/components/Frontend/Dispositif/LeftSideDispositif/LeftSideDispositif.tsx
  client/src/components/Layout/Layout.tsx
  client/src/components/Pages/dispositif/ContribCaroussel/ContribCaroussel.module.scss
  client/src/components/Pages/dispositif/ContribCaroussel/ContribCaroussel.tsx
  client/src/components/UI/FButton/FButton.module.scss
  client/src/components/UI/FButton/FButton.tsx
  client/src/containers/Backend/Admin/Admin.tsx
  client/src/containers/Backend/Dashboard/Dashboard.tsx
  client/src/containers/Backend/UserContributions/UserContributions.tsx
  client/src/containers/Backend/UserContributions/__tests__/__snapshots__/UserContributions.component.test.tsx.snap
  client/src/containers/Backend/UserFavorites/UserFavorites.tsx
  client/src/containers/Backend/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  client/src/containers/Backend/UserNotifications/UserNotifications.tsx
  client/src/containers/Backend/UserNotifications/__tests__/__snapshots__/UserNotifications.test.tsx.snap
  client/src/containers/Backend/UserProfile/UserProfile.tsx
  client/src/containers/Backend/UserProfile/__test__/__snapshots__/UserProfile.component.test.tsx.snap
  client/src/containers/Backend/UserStructure/UserStructure.component.tsx
  client/src/containers/Backend/UserStructure/UserStructureAdmin.component.tsx
  client/src/containers/Backend/UserStructure/__tests__/__snapshots__/UserStructure.test.tsx.snap
  client/src/containers/Backend/UserTranslation/UserTranslation.tsx
  client/src/containers/Backend/UserTranslation/__tests__/__snapshots__/UserTranslation.component.test.tsx.snap
  client/src/containers/Backend/routes.ts
  client/src/containers/Translation/Translation.js
  client/src/pages/backend/[...backend].tsx
  server/src/controllers/account/lib.js
Labels: release

#1171 [STG-FRONT] Release
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.module.scss
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.tsx
  client/src/components/Layout/Layout.tsx
  client/src/containers/Backend/Admin/Admin.tsx
  client/src/containers/Backend/Dashboard/Dashboard.tsx
  client/src/containers/Backend/UserContributions/UserContributions.tsx
  client/src/containers/Backend/UserFavorites/UserFavorites.tsx
  client/src/containers/Backend/UserNotifications/UserNotifications.tsx
  client/src/containers/Backend/UserProfile/UserProfile.tsx
  client/src/containers/Backend/UserStructure/UserStructure.component.tsx
  client/src/containers/Backend/UserStructure/UserStructureAdmin.component.tsx
  client/src/containers/Backend/UserTranslation/UserTranslation.tsx
  client/src/containers/Backend/routes.ts
  client/src/containers/Translation/Translation.js
  client/src/pages/backend/[...backend].tsx
  server/src/controllers/account/lib.js
Labels: release

#1173 [STG-FRONT] Release
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/components/Layout/Layout.scss
  client/src/scss/pages/dispositif.scss
Labels: release

#1174 Bugfixes
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.tsx
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/components/Frontend/Dispositif/LeftSideDispositif/LeftSideDispositif.tsx
  client/src/components/Modals/PdfCreateModal/PdfCreateModal.tsx
Labels: bug

#1175 [STG-FRONT] Release
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.tsx
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/components/Frontend/Dispositif/LeftSideDispositif/LeftSideDispositif.tsx
  client/src/components/Modals/PdfCreateModal/PdfCreateModal.tsx
Labels: release

#1179 [STG-BACK] Release
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.tsx
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/components/Frontend/Dispositif/LeftSideDispositif/LeftSideDispositif.tsx
  client/src/components/Layout/Layout.scss
  client/src/components/Modals/PdfCreateModal/PdfCreateModal.tsx
  client/src/scss/pages/dispositif.scss
  server/Dockerfile
Labels: release

#1180 [STG-BACK] Release
  server/Dockerfile
Labels: release

#1181 [PROD-BACK] Release
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.tsx
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/components/Frontend/Dispositif/LeftSideDispositif/LeftSideDispositif.tsx
  client/src/components/Layout/Layout.scss
  client/src/components/Modals/PdfCreateModal/PdfCreateModal.tsx
  client/src/scss/pages/dispositif.scss
  server/Dockerfile
Labels: release

#1176 add stats on AdminContenu screen
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  client/src/containers/Backend/Admin/AdminContenu/components/LoadingAdminContenu.tsx
  client/src/containers/Backend/Admin/AdminContenu/data.ts
  client/src/types/interface.d.ts
  server/src/modules/dispositif/__tests__/dispositif.adapter.test.ts
  server/src/modules/dispositif/dispositif.adapter.ts
  server/src/workflows/dispositif/getAllDispositifs/getAllDispositifs.test.ts
  server/src/workflows/dispositif/getAllDispositifs/getAllDispositifs.ts
Labels: enhancement

#1183 fix search mobile ln button
  client/src/components/Pages/advanced-search/MobileAdvancedSearch/MobileSearchFilterModal/MobileSearchFilterModal.tsx
  client/src/components/Pages/advanced-search/MobileAdvancedSearch/SelectedFilter/SelectedFilter.tsx
  client/src/components/UI/Language/Language.tsx
Labels: bug

#1184 fix pdf print on demarches
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.tsx
  client/src/components/Pages/dispositif/EtapeParagraphe/EtapeParagraphe.tsx
  client/src/components/Pages/dispositif/QuickToolbar/QuickToolbar.module.scss
  client/src/scss/mixins/_responsive.scss
  client/src/scss/pages/dispositif.module.scss
Labels: bug

#1186 [STG-BACK] Release
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.tsx
  client/src/components/Pages/advanced-search/MobileAdvancedSearch/MobileSearchFilterModal/MobileSearchFilterModal.tsx
  client/src/components/Pages/advanced-search/MobileAdvancedSearch/SelectedFilter/SelectedFilter.tsx
  client/src/components/Pages/dispositif/EtapeParagraphe/EtapeParagraphe.tsx
  client/src/components/Pages/dispositif/QuickToolbar/QuickToolbar.module.scss
  client/src/components/UI/Language/Language.tsx
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  client/src/containers/Backend/Admin/AdminContenu/components/LoadingAdminContenu.tsx
  client/src/containers/Backend/Admin/AdminContenu/data.ts
  client/src/scss/mixins/_responsive.scss
  client/src/scss/pages/dispositif.module.scss
  client/src/types/interface.d.ts
  server/src/modules/dispositif/__tests__/dispositif.adapter.test.ts
  server/src/modules/dispositif/dispositif.adapter.ts
  server/src/workflows/dispositif/getAllDispositifs/getAllDispositifs.test.ts
  server/src/workflows/dispositif/getAllDispositifs/getAllDispositifs.ts
Labels: release

#1187 Bug export airtable
  client/package.json
  client/public/google4bbafba0b0553522.html
  server/package.json
  server/src/workflows/dispositif/exportFiches/exportFiches.ts
Labels: bug

#1189 [STG-BACK] Release
  client/package.json
  client/public/google4bbafba0b0553522.html
  server/package.json
  server/src/workflows/dispositif/exportFiches/exportFiches.ts
Labels: release

#1188 [STG-FRONT] Release
  client/package.json
  client/public/google4bbafba0b0553522.html
  server/package.json
  server/src/workflows/dispositif/exportFiches/exportFiches.ts
Labels: release

#1190 [PROD-BACK] Release
  client/package.json
  client/public/google4bbafba0b0553522.html
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.tsx
  client/src/components/Pages/advanced-search/MobileAdvancedSearch/MobileSearchFilterModal/MobileSearchFilterModal.tsx
  client/src/components/Pages/advanced-search/MobileAdvancedSearch/SelectedFilter/SelectedFilter.tsx
  client/src/components/Pages/dispositif/EtapeParagraphe/EtapeParagraphe.tsx
  client/src/components/Pages/dispositif/QuickToolbar/QuickToolbar.module.scss
  client/src/components/UI/Language/Language.tsx
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  client/src/containers/Backend/Admin/AdminContenu/components/LoadingAdminContenu.tsx
  client/src/containers/Backend/Admin/AdminContenu/data.ts
  client/src/scss/mixins/_responsive.scss
  client/src/scss/pages/dispositif.module.scss
  client/src/types/interface.d.ts
  server/package.json
  server/src/modules/dispositif/__tests__/dispositif.adapter.test.ts
  server/src/modules/dispositif/dispositif.adapter.ts
  server/src/workflows/dispositif/exportFiches/exportFiches.ts
  server/src/workflows/dispositif/getAllDispositifs/getAllDispositifs.test.ts
  server/src/workflows/dispositif/getAllDispositifs/getAllDispositifs.ts
Labels: release

#1191 [PROD-FRONT] Release
  client/package.json
  client/public/google4bbafba0b0553522.html
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.tsx
  client/src/components/Pages/advanced-search/MobileAdvancedSearch/MobileSearchFilterModal/MobileSearchFilterModal.tsx
  client/src/components/Pages/advanced-search/MobileAdvancedSearch/SelectedFilter/SelectedFilter.tsx
  client/src/components/Pages/dispositif/EtapeParagraphe/EtapeParagraphe.tsx
  client/src/components/Pages/dispositif/QuickToolbar/QuickToolbar.module.scss
  client/src/components/UI/Language/Language.tsx
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  client/src/containers/Backend/Admin/AdminContenu/components/LoadingAdminContenu.tsx
  client/src/containers/Backend/Admin/AdminContenu/data.ts
  client/src/scss/mixins/_responsive.scss
  client/src/scss/pages/dispositif.module.scss
  client/src/types/interface.d.ts
  server/Dockerfile
  server/package.json
  server/src/modules/dispositif/__tests__/dispositif.adapter.test.ts
  server/src/modules/dispositif/dispositif.adapter.ts
  server/src/workflows/dispositif/exportFiches/exportFiches.ts
  server/src/workflows/dispositif/getAllDispositifs/getAllDispositifs.test.ts
  server/src/workflows/dispositif/getAllDispositifs/getAllDispositifs.ts
Labels: release

#1193 fix upload image
  server/package-lock.json
  server/package.json
Labels: bug

#1194 [STG-BACK] Release
  server/package-lock.json
  server/package.json
Labels: release

#1196 bugfix logs
  server/src/workflows/dispositif/updateDispositifAdminComments/log.ts
  server/src/workflows/structure/updateStructure/log.ts
Labels: bug

#1197 [STG-BACK] Release
  server/src/workflows/dispositif/updateDispositifAdminComments/log.ts
  server/src/workflows/structure/updateStructure/log.ts
Labels: release

#1198 bugfix 413
  server/src/server.ts
Labels: bug

#1199 [STG-BACK] Release
  server/src/server.ts
Labels: release

#1200 bugfix log structure
  server/src/workflows/dispositif/modifyDispositifMainSponsor/log.ts
Labels: bug

#1201 [STG-BACK] Release
  server/src/workflows/dispositif/modifyDispositifMainSponsor/log.ts
Labels: release

#1203 fix redirect with qr code
  client/src/pages/_middleware.ts
Labels: bug

#1206 limit requests on admin
  client/src/components/Backend/Admin/CustomTabPane.tsx
  client/src/containers/Backend/Admin/Admin.tsx
  client/src/containers/Backend/Admin/AdminContenu/ChangeStructureModale/ChangeStructureModale.tsx
  client/src/containers/Backend/Admin/AdminContenu/ContentDetailsModal/ContentDetailsModal.tsx
  client/src/containers/Backend/Admin/AdminStructures/StructureDetailsModal/StructureDetailsModal.tsx
  client/src/containers/Backend/Admin/AdminUsers/UserDetailsModal/UserDetailsModal.tsx
  client/src/containers/Backend/Dashboard/Dashboard.tsx
Labels: bug

#1164 Update directory sheet
  client/.vscode/launch.json
  client/src/components/Pages/annuaire-create/Step1.tsx
  client/src/components/Pages/annuaire-create/Step2.tsx
  client/src/components/Pages/annuaire-create/Step3.tsx
  client/src/components/Pages/annuaire-create/Step4.tsx
  client/src/components/Pages/annuaire-create/Step5.tsx
  client/src/components/Pages/annuaire/id/LeftAnnuaireDetail.tsx
  client/src/components/Pages/annuaire/id/MiddleAnnuaireDetails.module.scss
  client/src/components/Pages/annuaire/id/MiddleAnnuaireDetails.tsx
  client/src/pages/annuaire-creation.tsx
  client/src/pages/annuaire/[id].tsx
  client/src/pages/annuaire/index.tsx
  client/src/scss/_colors.scss
  client/src/services/LoadingStatus/loadingStatus.actions.ts
  client/src/services/SelectedStructure/__tests__/selectedStructure.saga.test.ts
  client/src/services/SelectedStructure/selectedStructure.actionTypes.ts
  client/src/services/SelectedStructure/selectedStructure.actions.ts
  client/src/services/SelectedStructure/selectedStructure.saga.ts
  client/src/services/SelectedStructure/selectedStructure.selector.ts
Labels: enhancement

#1210 Fix modal content
  client/src/containers/Backend/Admin/AdminContenu/ContentDetailsModal/ContentDetailsModal.tsx
  client/src/containers/Backend/Admin/AdminStructures/AdminStructures.tsx
  client/src/containers/Backend/Admin/AdminStructures/StructureDetailsModal/StructureDetailsModal.tsx
  client/src/containers/Backend/Admin/AdminUsers/UserDetailsModal/UserDetailsModal.tsx
  client/src/containers/Backend/Admin/Needs/lib.ts
  server/src/modules/logs/logs.service.ts
  server/src/workflows/users/updateUser/log.ts
  server/src/workflows/users/updateUser/updateUser.ts
Labels: bug

#1211 [STG-FRONT] Release
  client/.vscode/launch.json
  client/src/components/Pages/annuaire-create/Step1.tsx
  client/src/components/Pages/annuaire-create/Step2.tsx
  client/src/components/Pages/annuaire-create/Step3.tsx
  client/src/components/Pages/annuaire-create/Step4.tsx
  client/src/components/Pages/annuaire-create/Step5.tsx
  client/src/components/Pages/annuaire/id/LeftAnnuaireDetail.tsx
  client/src/components/Pages/annuaire/id/MiddleAnnuaireDetails.module.scss
  client/src/components/Pages/annuaire/id/MiddleAnnuaireDetails.tsx
  client/src/containers/Backend/Admin/AdminContenu/ContentDetailsModal/ContentDetailsModal.tsx
  client/src/containers/Backend/Admin/AdminStructures/AdminStructures.tsx
  client/src/containers/Backend/Admin/AdminStructures/StructureDetailsModal/StructureDetailsModal.tsx
  client/src/containers/Backend/Admin/AdminUsers/UserDetailsModal/UserDetailsModal.tsx
  client/src/containers/Backend/Admin/Needs/lib.ts
  client/src/pages/annuaire-creation.tsx
  client/src/pages/annuaire/[id].tsx
  client/src/pages/annuaire/index.tsx
  client/src/scss/_colors.scss
  client/src/services/LoadingStatus/loadingStatus.actions.ts
  client/src/services/SelectedStructure/__tests__/selectedStructure.saga.test.ts
  client/src/services/SelectedStructure/selectedStructure.actionTypes.ts
  client/src/services/SelectedStructure/selectedStructure.actions.ts
  client/src/services/SelectedStructure/selectedStructure.saga.ts
  client/src/services/SelectedStructure/selectedStructure.selector.ts
  server/src/modules/logs/logs.service.ts
  server/src/workflows/users/updateUser/log.ts
  server/src/workflows/users/updateUser/updateUser.ts
Labels: release
