Repository refugies-info/karfur, pull requests merged in 2022-12, with the labels that each got.

#1390 fix: :bug: remove demarches from otherDispositifsWithTheme
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/lib/recherche/filterContents.ts
  client/src/lib/recherche/queryContents.ts
  client/src/types/interface.d.ts
Labels: bug

#1391 [STG-FRONT] Release
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/lib/recherche/filterContents.ts
  client/src/lib/recherche/queryContents.ts
  client/src/types/interface.d.ts
Labels: release

#1392 feat: :sparkles: add write content modal
  client/src/assets/assetsOnServer.ts
  client/src/assets/publier/orange_bg.svg
  client/src/assets/publier/red_bg.svg
  client/src/components/Modals/NewSearchModal/NewSearchModal.tsx
  client/src/components/Modals/WriteContentModal/WriteContentModal.module.scss
  client/src/components/Modals/WriteContentModal/WriteContentModal.tsx
  client/src/components/Pages/publier/Register/Register.tsx
  client/src/components/Pages/publier/WriteContentCard/WriteContentCard.module.scss
  client/src/components/Pages/publier/WriteContentCard/WriteContentCard.tsx
  client/src/components/Pages/publier/WriteContentCard/index.ts
  client/src/locales/ar/common.json
  client/src/locales/en/common.json
  client/src/locales/fa/common.json
  client/src/locales/fr/common.json
  client/src/locales/ps/common.json
  client/src/locales/ru/common.json
  client/src/locales/ti/common.json
  client/src/pages/publier.tsx
Labels: enhancement

#1397 [PROD-FRONT] Release
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/lib/recherche/filterContents.ts
  client/src/lib/recherche/queryContents.ts
  client/src/types/interface.d.ts
Labels: release

#1403 [STG-FRONT] Release
  client/Dockerfile
Labels: release

#1406 [STG-FRONT] Release
  server/src/workflows/dispositif/addDispositif/addDispositif.test.ts
  server/src/workflows/dispositif/addDispositif/addDispositif.ts
Labels: release

#1408 [STG-FRONT] Release
  client/package-lock.json
  client/package.json
  client/src/components/Pages/annuaire/index/Header.tsx
  client/src/components/Pages/annuaire/index/SearchBarAnnuaire.tsx
  client/src/pages/annuaire/index.tsx
  client/src/scss/index.scss
Labels: release

#1412 [STG-FRONT] Release
  client/redirects.js
  client/src/assets/diair.svg
  client/src/assets/index.ts
  client/src/components/Frontend/Dispositif/BandeauEdition/BandeauEdition.module.scss
  client/src/components/Frontend/Dispositif/EnBrefBanner/EnBrefBanner.tsx
  client/src/components/Layout/Footer/FooterDSFR.tsx
  client/src/components/Modals/DispositifCreateModal/DispositifCreateModal.module.scss
  client/src/components/Navigation/Navbar/FrontendNavigation/FrontendNavigation.tsx
  client/src/components/Navigation/Navbar/FrontendNavigation/index.ts
  client/src/components/Navigation/Navbar/NavbarDSFR.tsx
  client/src/components/Navigation/Navbar/NavbarItems/SubscribeToolItem/SubscribeToolItem.tsx
  client/src/components/Navigation/Navbar/NavbarItems/UserToolItem/UserToolItem.tsx
  client/src/components/Pages/annuaire/index/Header.module.scss
  client/src/components/Pages/dispositif/SideTrad/ExpertSideTrad.js
  client/src/components/Pages/dispositif/SideTrad/SideTrad.js
  client/src/components/Pages/dispositif/SideTrad/SideTrad.module.scss
  client/src/components/Pages/recherche/SecondaryFilter/SecondaryFilter.desktop.module.scss
  client/src/components/UI/DemarcheCard/DemarcheCard.module.scss
  client/src/components/UI/FButton/FButton.module.scss
  client/src/containers/Backend/Admin/Admin.module.scss
  client/src/containers/Backend/Admin/Needs/Needs.tsx
  client/src/containers/Backend/Admin/sharedComponents/StyledAdmin.ts
  client/src/containers/Backend/Navigation/NavItems/BackendNavItem/BackendNavItem.tsx
  client/src/containers/Backend/Navigation/NavigationDSFR.module.scss
  client/src/containers/Backend/UserNotifications/UserNotifications.tsx
  client/src/containers/Backend/UserNotifications/__tests__/__snapshots__/UserNotifications.test.tsx.snap
  client/src/containers/Backend/UserTranslation/components/TranslationLanguagesChoiceModal.module.scss
  client/src/containers/Backend/UserTranslation/components/TranslationLanguagesChoiceModal.tsx
  client/src/locales/fr/common.json
  client/src/pages/plan-du-site.tsx
  client/src/routes.ts
  client/src/scss/_dsfr-fix.scss
  client/src/scss/mixins/_text.scss
  client/src/scss/pages/dispositif.scss
  client/src/types/window.d.ts
Labels: release

#1416 [STG-FRONT] Release
  client/src/components/Frontend/Dispositif/MapComponent/MapComponent.module.scss
Labels: release

#1417 [STG-FRONT] Release
  client/public/video/publier-video-why2.mp4
  client/public/video/publier-video-why3.mp4
  client/src/__tests__/__snapshots__/publier.test.tsx.snap
  client/src/__tests__/__snapshots__/traduire.test.tsx.snap
  client/src/assets/staticPages/publier/why-image-2.png
  client/src/assets/staticPages/publier/why-image-3.png
  client/src/components/Navigation/Navbar/FrontendNavigation/FrontendNavigation.tsx
  client/src/components/Pages/staticPages/common/Accordion/Accordion.module.scss
  client/src/components/Pages/staticPages/common/Accordion/Accordion.tsx
  client/src/components/Pages/staticPages/common/AutoplayVideo/AutoplayVideo.tsx
  client/src/components/Pages/staticPages/common/InlineLink/InlineLink.tsx
  client/src/components/Pages/staticPages/common/Register/Register.module.scss
  client/src/components/Pages/staticPages/common/Register/Register.tsx
  client/src/components/Pages/staticPages/common/SecondaryNavbar/SecondaryNavbar.module.scss
  client/src/components/Pages/staticPages/common/StepContent/StepContent.module.scss
  client/src/components/Pages/staticPages/publier/WriteContentCard/WriteContentCard.module.scss
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  client/src/containers/Backend/UserContributions/UserContributions.tsx
  client/src/containers/Backend/UserContributions/__tests__/__snapshots__/UserContributions.component.test.tsx.snap
  client/src/containers/Backend/UserContributions/components/NoContribution.tsx
  client/src/locales/fr/common.json
  client/src/pages/index.tsx
  client/src/pages/publier.tsx
  client/src/pages/traduire.tsx
  client/src/scss/components/staticPages.module.scss
Labels: release

#1418 fix: :bug: various fixes
  client/src/__tests__/__snapshots__/publier.test.tsx.snap
  client/src/__tests__/__snapshots__/traduire.test.tsx.snap
  client/src/components/Layout/Footer.module.scss
  client/src/components/Layout/Footer/FooterDSFR.module.scss
  client/src/components/Layout/Footer/FooterDSFR.tsx
  client/src/components/Pages/staticPages/common/Accordion/Accordion.module.scss
  client/src/components/Pages/staticPages/common/Accordion/Accordion.tsx
  client/src/components/Pages/staticPages/common/SecondaryNavbar/SecondaryNavbar.module.scss
  client/src/components/Pages/staticPages/common/StepContent/StepContent.module.scss
  client/src/locales/fr/common.json
  client/src/pages/traduire.tsx
  client/src/scss/components/staticPages.module.scss
Labels: bug

#1419 [STG-FRONT] Release
  client/src/__tests__/__snapshots__/publier.test.tsx.snap
  client/src/__tests__/__snapshots__/traduire.test.tsx.snap
  client/src/components/Layout/Footer.module.scss
  client/src/components/Layout/Footer/FooterDSFR.module.scss
  client/src/components/Layout/Footer/FooterDSFR.tsx
  client/src/components/Pages/staticPages/common/Accordion/Accordion.module.scss
  client/src/components/Pages/staticPages/common/Accordion/Accordion.tsx
  client/src/components/Pages/staticPages/common/SecondaryNavbar/SecondaryNavbar.module.scss
  client/src/components/Pages/staticPages/common/StepContent/StepContent.module.scss
  client/src/locales/fr/common.json
  client/src/pages/traduire.tsx
  client/src/scss/components/staticPages.module.scss
Labels: release

#1420 fix: :bug: last minor fixes
  client/src/__tests__/__snapshots__/publier.test.tsx.snap
  client/src/__tests__/__snapshots__/traduire.test.tsx.snap
  client/src/components/Pages/staticPages/common/AutoplayVideo/AutoplayVideo.tsx
  client/src/components/Pages/staticPages/common/SecondaryNavbar/SecondaryNavbar.module.scss
  client/src/pages/publier.tsx
  client/src/pages/traduire.tsx
Labels: bug

#1421 [STG-FRONT] Release
  client/src/__tests__/__snapshots__/publier.test.tsx.snap
  client/src/__tests__/__snapshots__/traduire.test.tsx.snap
  client/src/components/Pages/staticPages/common/AutoplayVideo/AutoplayVideo.tsx
  client/src/components/Pages/staticPages/common/SecondaryNavbar/SecondaryNavbar.module.scss
  client/src/pages/publier.tsx
  client/src/pages/traduire.tsx
Labels: release

#1423 [STG-FRONT] Release
  client/src/__tests__/__snapshots__/publier.test.tsx.snap
  client/src/__tests__/__snapshots__/traduire.test.tsx.snap
  client/src/components/Pages/staticPages/common/AutoplayVideo/AutoplayVideo.tsx
Labels: release

#1427 [STG-FRONT] Release
  client/src/components/Navigation/Navbar/NavbarDSFR.tsx
Labels: release

#1431 [STG-FRONT] Release
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.tsx
  client/src/components/UI/DispositifCard/DispositifCard.module.scss
  client/src/components/UI/ThemeBadge/ThemeBadge.module.scss
  client/src/pages/index.tsx
  client/src/scss/components/contentCard.module.scss
  client/src/scss/pages/homepage.module.scss
Labels: release

#1436 [STG-FRONT] Release
  client/src/__tests__/publier.test.tsx
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/components/Frontend/Dispositif/FeedbackFooter/FeedbackFooter.tsx
  client/src/components/Frontend/Dispositif/Sponsors/Sponsors.tsx
  client/src/components/Layout/Footer/FooterDSFR.tsx
  client/src/components/Modals/CompleteProfilModal/CompleteProfilModal.tsx
  client/src/components/Modals/WriteContentModal/WriteContentModal.tsx
  client/src/components/Navigation/Navbar/NavbarDSFR.tsx
  client/src/components/Pages/annuaire/id/RightAnnuaireDetails.tsx
  client/src/components/Pages/dispositif/SideTrad/ExpertSideTrad.js
  client/src/components/Pages/dispositif/SideTrad/SideTrad.js
  client/src/components/Pages/homepage/MobileAppSection.module.scss
  client/src/components/Pages/homepage/MobileAppSection.tsx
  client/src/containers/Backend/Admin/sharedComponents/StyledAdmin.ts
  client/src/containers/Backend/UserContributions/__tests__/UserContributions.component.test.tsx
  client/src/containers/Backend/UserNotifications/UserNotifications.tsx
  client/src/containers/Backend/UserNotifications/__tests__/UserNotifications.test.tsx
  client/src/containers/Backend/UserTranslation/UserTranslation.tsx
  client/src/lib/recherche/queryContents.ts
  client/src/locales/ar/common.json
  client/src/locales/ar/unused.json
  client/src/locales/en/common.json
  client/src/locales/en/unused.json
  client/src/locales/fa/common.json
  client/src/locales/fa/unused.json
  client/src/locales/fr/common.json
  client/src/locales/fr/unused.json
  client/src/locales/ps/common.json
  client/src/locales/ps/unused.json
  client/src/locales/ru/common.json
  client/src/locales/ru/unused.json
  client/src/locales/ti/common.json
  client/src/locales/ti/unused.json
  client/src/locales/uk/common.json
  client/src/locales/uk/unused.json
  client/src/pages/annuaire/[id].tsx
  client/src/pages/index.tsx
  client/src/scss/_dsfr-fix.scss
  client/src/scss/components/login.module.scss
  client/src/scss/pages/dispositif.scss
  client/src/scss/pages/homepage.module.scss
Labels: release

#1438 [STG-FRONT] Release
  client/src/__tests__/__snapshots__/recherche.test.tsx.snap
  client/src/components/Frontend/Dispositif/FeedbackFooter/FeedbackFooter.tsx
  client/src/components/Frontend/Dispositif/Sponsors/Sponsors.tsx
  client/src/components/Modals/DemarcheCreateModal/DemarcheCreateModal.module.scss
  client/src/components/Modals/DemarcheCreateModal/DemarcheCreateModal.tsx
  client/src/components/Modals/index.ts
  client/src/components/Navigation/Navbar/NavbarItems/SpeekToolItem/SpeekToolItem.tsx
  client/src/components/Pages/dispositif/ContribCaroussel/ContribCaroussel.module.scss
  client/src/components/Pages/dispositif/SideTrad/ExpertSideTrad.js
  client/src/components/Pages/dispositif/SideTrad/SideTrad.js
  client/src/components/Pages/homepage/MobileAppSection.module.scss
  client/src/components/Pages/recherche/SearchResults/SearchResults.module.scss
  client/src/components/Pages/recherche/SearchResults/SearchResults.tsx
  client/src/containers/Backend/Dashboard/Dashboard.tsx
  client/src/data/dispositif.tsx
  client/src/scss/_common.scss
  client/src/scss/_variables.scss
Labels: release

#1439 fix: :bug: fix open write modal
  client/src/components/Modals/WriteContentModal/WriteContentModal.tsx
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  client/src/containers/Backend/UserContributions/UserContributions.tsx
  client/src/pages/publier.tsx
Labels: bug

#1443 fix: :lipstick: minor design fixes
  client/src/components/Pages/homepage/Sections/Infos/Infos.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppIllu/MobileAppIllu.module.scss
  client/src/components/Pages/homepage/Sections/NewContent/NewContent.module.scss
  client/src/components/Pages/recherche/CardSlider/CardSlider.tsx
Labels: bug

#1444 [STG-FRONT] Release
  client/src/components/Pages/homepage/Sections/Infos/Infos.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppIllu/MobileAppIllu.module.scss
  client/src/components/Pages/homepage/Sections/NewContent/NewContent.module.scss
  client/src/components/Pages/recherche/CardSlider/CardSlider.tsx
Labels: release

#1445 fix: :bug: fix home content type
  client/src/components/Pages/homepage/Sections/NewContent/NewContent.tsx
Labels: bug

#1446 [STG-FRONT] Release
  client/src/components/Pages/homepage/Sections/NewContent/NewContent.tsx
Labels: release

#1379 fix: SEO with priority 5
  client/src/components/Frontend/Dispositif/ContenuDispositif/ContenuDispositif.tsx
  client/src/components/Frontend/Dispositif/ContenuParagraphe/ContenuParagraphe.tsx
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/components/Frontend/Dispositif/FeedbackFooter/FeedbackFooter.module.scss
  client/src/components/Frontend/Dispositif/FeedbackFooter/FeedbackFooter.tsx
  client/src/components/Frontend/Dispositif/Sponsors/Sponsors.module.scss
  client/src/components/Frontend/Dispositif/Sponsors/Sponsors.tsx
  client/src/components/Modals/EtapeModal/EtapeModal.module.scss
  client/src/components/Modals/EtapeModal/EtapeModal.tsx
  client/src/components/Modals/index.ts
  client/src/components/Pages/annuaire/id/MiddleAnnuaireDetails.tsx
  client/src/components/Pages/annuaire/index/LetterSection.module.scss
  client/src/components/Pages/annuaire/index/LetterSection.tsx
  client/src/components/Pages/dispositif/ContribCaroussel/ContribCaroussel.module.scss
  client/src/components/Pages/dispositif/ContribCaroussel/ContribCaroussel.tsx
  client/src/components/Pages/dispositif/EtapeParagraphe/EtapeParagraphe.module.scss
  client/src/components/Pages/dispositif/EtapeParagraphe/EtapeParagraphe.tsx
  client/src/components/UI/DemarcheCard/DemarcheCard.tsx
  client/src/components/UI/DispositifCard/DispositifCard.tsx
  client/src/containers/Backend/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  client/src/data/dispositif.tsx
  client/src/scss/pages/dispositif.scss
Labels: bug

#1447 fix: homepage bugs
  client/src/__fixtures__/getDispositifs.ts
  client/src/__tests__/__snapshots__/index.test.tsx.snap
  client/src/__tests__/index.test.tsx
  client/src/assets/homepage/app-mockup.png
  client/src/assets/homepage/app-qr-code.png
  client/src/assets/homepage/helpus-icon-1.png
  client/src/assets/homepage/helpus-icon-3.svg
  client/src/assets/homepage/newsletter-illu.svg
  client/src/assets/homepage/usages-mobile.png
  client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.desktop.module.scss
  client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.tsx
  client/src/components/Pages/homepage/Sections/NewContent/NewContent.tsx
  client/src/components/Pages/recherche/SearchInput/SearchInput.module.scss
  client/src/containers/Backend/Dashboard/Dashboard.tsx
  client/src/pages/index.tsx
  client/src/pages/publier.tsx
  client/src/pages/traduire.tsx
  client/src/scss/components/searchHeader.module.scss
  client/src/types/interface.d.ts
  client/src/utils/API.ts
  server/src/controllers/dispositifController.js
  server/src/controllers/structureController.js
  server/src/controllers/traductionController.js
  server/src/modules/dispositif/__tests__/dispositif.repository.test.ts
  server/src/modules/dispositif/dispositif.repository.ts
  server/src/workflows/dispositif/getDispositifs/getDispositifs.test.ts
  server/src/workflows/dispositif/getDispositifs/getDispositifs.ts
  server/src/workflows/dispositif/getDispositifs/index.ts
  server/src/workflows/dispositif/getStatistics/getStatistics.test.ts
  server/src/workflows/dispositif/getStatistics/getStatistics.ts
  server/src/workflows/dispositif/getStatistics/index.ts
  server/src/workflows/structure/getStatistics/getStatistics.test.ts
  server/src/workflows/structure/getStatistics/getStatistics.ts
  server/src/workflows/structure/getStatistics/index.ts
  server/src/workflows/translation/getStatistics/getStatistics.test.ts
  server/src/workflows/translation/getStatistics/getStatistics.ts
  server/src/workflows/translation/getStatistics/index.ts
Labels: bug

#1451 fix: :mag: fix meta url and images paths
  client/src/components/Seo.tsx
  client/src/lib/getBaseUrl.ts
Labels: bug

#1452 refactor: :art: refactor and move home components
  client/src/__tests__/__snapshots__/index.test.tsx.snap
  client/src/__tests__/__snapshots__/publier.test.tsx.snap
  client/src/assets/figma/index.ts
  client/src/assets/figma/integration_illu.svg
  client/src/assets/figma/interieur_2.svg
  client/src/assets/figma/interieur_3.svg
  client/src/assets/figma/interieur_4.svg
  client/src/assets/figma/logo_mobile.svg
  client/src/assets/figma/trame_home_bg.svg
  client/src/assets/homepage/hero/background-image.svg
  client/src/assets/homepage/hero/bottom-back.svg
  client/src/assets/homepage/hero/character.svg
  client/src/components/Logo/Logo.module.scss
  client/src/components/Logo/Logo.tsx
  client/src/components/Modals/GoToDesktopModal/GoToDesktopModal.tsx
  client/src/components/Modals/GoToDesktopModal/index.ts
  client/src/components/Modals/ReceiveInvitationMailModal/ReceiveInvitationMailModal.tsx
  client/src/components/Modals/ReceiveInvitationMailModal/index.ts
  client/src/components/Modals/WriteContentModal/WriteContentCard/WriteContentCard.module.scss
  client/src/components/Modals/WriteContentModal/WriteContentCard/WriteContentCard.tsx
  client/src/components/Modals/WriteContentModal/WriteContentCard/index.ts
  client/src/components/Modals/WriteContentModal/WriteContentModal.tsx
  client/src/components/Modals/index.ts
  client/src/components/Pages/homepage/CommunityCard/CommunityCard.module.scss
  client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.mobile.tsx
  client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.tsx
  client/src/components/Pages/homepage/Sections/HelpUs/HelpUs.tsx
  client/src/components/Pages/homepage/Sections/Hero/Hero.module.scss
  client/src/components/Pages/homepage/Sections/Hero/Hero.tsx
  client/src/components/Pages/homepage/Sections/MainFigures/MainFigures.tsx
  client/src/components/Pages/homepage/Sections/NewContent/NewContent.module.scss
  client/src/components/Pages/recherche/HomeSearch/HomeSearch.module.scss
  client/src/components/Pages/recherche/NotDeployedBanner/NotDeployedBanner.tsx
  client/src/components/Pages/staticPages/common/Accordion/Accordion.module.scss
  client/src/components/Pages/staticPages/common/Accordion/Accordion.tsx
  client/src/components/Pages/staticPages/common/CountUpFigure/CountUpFigure.module.scss
  client/src/components/Pages/staticPages/common/CountUpFigure/CountUpFigure.tsx
  client/src/components/Pages/staticPages/common/CountUpFigure/index.ts
  client/src/components/Pages/staticPages/common/HeroArrow/HeroArrow.module.scss
  client/src/components/Pages/staticPages/common/LanguageIcon/LanguageIcon.module.scss
  client/src/components/Pages/staticPages/common/LanguageIcon/LanguageIcon.tsx
  client/src/components/Pages/staticPages/common/LanguageIcon/index.ts
  client/src/components/Pages/staticPages/common/Register/Register.tsx
  client/src/components/Pages/staticPages/common/index.ts
  client/src/components/Pages/staticPages/publier/index.ts
  client/src/pages/publier.tsx
  client/src/pages/traduire.tsx
Labels: enhancement

#1454 [STG-FRONT] Release
  client/src/__tests__/__snapshots__/index.test.tsx.snap
  client/src/__tests__/__snapshots__/publier.test.tsx.snap
  client/src/assets/figma/index.ts
  client/src/assets/figma/integration_illu.svg
  client/src/assets/figma/interieur_2.svg
  client/src/assets/figma/interieur_3.svg
  client/src/assets/figma/interieur_4.svg
  client/src/assets/figma/logo_mobile.svg
  client/src/assets/figma/trame_home_bg.svg
  client/src/assets/homepage/hero/background-image.svg
  client/src/assets/homepage/hero/bottom-back.svg
  client/src/assets/homepage/hero/character.svg
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/components/Logo/Logo.module.scss
  client/src/components/Logo/Logo.tsx
  client/src/components/Modals/GoToDesktopModal/GoToDesktopModal.tsx
  client/src/components/Modals/GoToDesktopModal/index.ts
  client/src/components/Modals/ReceiveInvitationMailModal/ReceiveInvitationMailModal.tsx
  client/src/components/Modals/ReceiveInvitationMailModal/index.ts
  client/src/components/Modals/WriteContentModal/WriteContentCard/WriteContentCard.module.scss
  client/src/components/Modals/WriteContentModal/WriteContentCard/WriteContentCard.tsx
  client/src/components/Modals/WriteContentModal/WriteContentCard/index.ts
  client/src/components/Modals/WriteContentModal/WriteContentModal.tsx
  client/src/components/Modals/index.ts
  client/src/components/Pages/homepage/CommunityCard/CommunityCard.module.scss
  client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.mobile.tsx
  client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.tsx
  client/src/components/Pages/homepage/Sections/HelpUs/HelpUs.tsx
  client/src/components/Pages/homepage/Sections/Hero/Hero.module.scss
  client/src/components/Pages/homepage/Sections/Hero/Hero.tsx
  client/src/components/Pages/homepage/Sections/MainFigures/MainFigures.tsx
  client/src/components/Pages/homepage/Sections/NewContent/NewContent.module.scss
  client/src/components/Pages/recherche/HomeSearch/HomeSearch.module.scss
  client/src/components/Pages/recherche/NotDeployedBanner/NotDeployedBanner.tsx
  client/src/components/Pages/staticPages/common/Accordion/Accordion.module.scss
  client/src/components/Pages/staticPages/common/Accordion/Accordion.tsx
  client/src/components/Pages/staticPages/common/CountUpFigure/CountUpFigure.module.scss
  client/src/components/Pages/staticPages/common/CountUpFigure/CountUpFigure.tsx
  client/src/components/Pages/staticPages/common/CountUpFigure/index.ts
  client/src/components/Pages/staticPages/common/HeroArrow/HeroArrow.module.scss
  client/src/components/Pages/staticPages/common/LanguageIcon/LanguageIcon.module.scss
  client/src/components/Pages/staticPages/common/LanguageIcon/LanguageIcon.tsx
  client/src/components/Pages/staticPages/common/LanguageIcon/index.ts
  client/src/components/Pages/staticPages/common/Register/Register.tsx
  client/src/components/Pages/staticPages/common/index.ts
  client/src/components/Pages/staticPages/publier/index.ts
  client/src/components/Seo.tsx
  client/src/lib/getBaseUrl.ts
  client/src/pages/publier.tsx
  client/src/pages/traduire.tsx
Labels: release

#1457 style: :lipstick: update padding and home image
  client/src/assets/homepage/hero/background-image.svg
  client/src/components/Pages/homepage/Sections/Hero/Hero.module.scss
Labels: bug

#1460 [STG-FRONT] Release
  client/src/assets/homepage/hero/background-image.svg
  client/src/components/Pages/homepage/Sections/Hero/Hero.module.scss
  server/package-lock.json
  server/src/libs/getDispositifDepartments.ts
  server/src/modules/dispositif/dispositif.repository.ts
  server/src/modules/structure/structure.repository.ts
  server/src/modules/users/users.repository.ts
  server/src/workflows/dispositif/getUserContributions/getUserContributions.ts
  server/src/workflows/mail/sendDraftReminderMail/sendDraftReminderMail.ts
  server/src/workflows/mail/sendReminderMailToUpdateContents/sendReminderMailToUpdateContents.ts
  server/src/workflows/structure/getActiveStructures/getActiveStructures.ts
  server/src/workflows/structure/getAllStructures/getAllStructures.test.ts
  server/src/workflows/structure/getAllStructures/getAllStructures.ts
  server/src/workflows/structure/getStructureById/getStructureById.ts
Labels: release

#1464 [STG-FRONT] Release
  client/src/components/Frontend/Dispositif/Dispositif.tsx
Labels: release

#1466 [STG-FRONT] Release
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  client/src/containers/Backend/Admin/AdminStructures/AdminStructures.tsx
  client/src/containers/Backend/Admin/AdminUsers/AdminUsers.tsx
  client/src/containers/Backend/Admin/Needs/Needs.tsx
  client/src/containers/Backend/Admin/sharedComponents/StyledAdmin.ts
Labels: release

#1458 style: :lipstick: static pages design
  client/src/__tests__/__snapshots__/index.test.tsx.snap
  client/src/__tests__/__snapshots__/publier.test.tsx.snap
  client/src/__tests__/__snapshots__/traduire.test.tsx.snap
  client/src/assets/homepage/app-qr-code.png
  client/src/components/Content/ThemesGrid/ThemesGrid.module.scss
  client/src/components/Pages/homepage/CommunityCard/CommunityCard.module.scss
  client/src/components/Pages/homepage/CommunityCard/CommunityCard.tsx
  client/src/components/Pages/homepage/Sections/Community/Community.module.scss
  client/src/components/Pages/homepage/Sections/Community/Community.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/LanguageDropdown/LanguageDropdown.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/LanguageDropdown/LanguageDropdown.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/LanguageDropdown/index.ts
  client/src/components/Pages/homepage/Sections/MobileApp/MobileApp.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/MobileApp.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppSmsForm/MobileAppSmsForm.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppSmsForm/MobileAppSmsForm.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppSmsForm/index.ts
  client/src/components/Pages/homepage/Sections/NewContent/NewContent.tsx
  client/src/components/Pages/homepage/Sections/WhyAccordions/WhyAccordions.tsx
  client/src/components/Pages/staticPages/common/Accordion/Accordion.module.scss
  client/src/components/Pages/staticPages/common/Accordion/Accordion.tsx
  client/src/components/Pages/staticPages/common/AutoplayVideo/AutoplayVideo.module.scss
  client/src/components/Pages/staticPages/common/AutoplayVideo/AutoplayVideo.tsx
  client/src/components/Pages/staticPages/common/InlineLink/InlineLink.module.scss
  client/src/components/Pages/staticPages/common/StepContent/StepContent.module.scss
  client/src/components/Pages/staticPages/common/StepContent/StepContent.tsx
  client/src/components/Pages/staticPages/traduire/LanguageCard/LanguageCard.module.scss
  client/src/locales/fr/common.json
  client/src/pages/publier.tsx
  client/src/scss/components/staticPages.module.scss
  client/src/scss/mixins/_text.scss
  client/src/utils/API.ts
  server/src/connectors/twilio/sendSMS.ts
  server/src/controllers/miscellaneous/sms.js
  server/src/controllers/smsController.js
  server/src/locales/fr/common.json
  server/src/server.ts
  server/src/workflows/sms/downloadApp/downloadApp.test.ts
  server/src/workflows/sms/downloadApp/downloadApp.ts
  server/src/workflows/sms/downloadApp/index.ts
Labels: bug

#1468 [STG-FRONT] Release
  client/src/__tests__/__snapshots__/index.test.tsx.snap
  client/src/__tests__/__snapshots__/publier.test.tsx.snap
  client/src/__tests__/__snapshots__/traduire.test.tsx.snap
  client/src/assets/homepage/app-qr-code.png
  client/src/components/Content/ThemesGrid/ThemesGrid.module.scss
  client/src/components/Pages/homepage/CommunityCard/CommunityCard.module.scss
  client/src/components/Pages/homepage/CommunityCard/CommunityCard.tsx
  client/src/components/Pages/homepage/Sections/Community/Community.module.scss
  client/src/components/Pages/homepage/Sections/Community/Community.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/LanguageDropdown/LanguageDropdown.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/LanguageDropdown/LanguageDropdown.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/LanguageDropdown/index.ts
  client/src/components/Pages/homepage/Sections/MobileApp/MobileApp.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/MobileApp.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppSmsForm/MobileAppSmsForm.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppSmsForm/MobileAppSmsForm.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppSmsForm/index.ts
  client/src/components/Pages/homepage/Sections/NewContent/NewContent.tsx
  client/src/components/Pages/homepage/Sections/WhyAccordions/WhyAccordions.tsx
  client/src/components/Pages/staticPages/common/Accordion/Accordion.module.scss
  client/src/components/Pages/staticPages/common/Accordion/Accordion.tsx
  client/src/components/Pages/staticPages/common/AutoplayVideo/AutoplayVideo.module.scss
  client/src/components/Pages/staticPages/common/AutoplayVideo/AutoplayVideo.tsx
  client/src/components/Pages/staticPages/common/InlineLink/InlineLink.module.scss
  client/src/components/Pages/staticPages/common/StepContent/StepContent.module.scss
  client/src/components/Pages/staticPages/common/StepContent/StepContent.tsx
  client/src/components/Pages/staticPages/traduire/LanguageCard/LanguageCard.module.scss
  client/src/locales/fr/common.json
  client/src/pages/publier.tsx
  client/src/scss/components/staticPages.module.scss
  client/src/scss/mixins/_text.scss
  client/src/utils/API.ts
  server/src/connectors/twilio/sendSMS.ts
  server/src/controllers/miscellaneous/sms.js
  server/src/controllers/smsController.js
  server/src/locales/fr/common.json
  server/src/server.ts
  server/src/workflows/sms/downloadApp/downloadApp.test.ts
  server/src/workflows/sms/downloadApp/downloadApp.ts
  server/src/workflows/sms/downloadApp/index.ts
Labels: release

#1470 [STG-FRONT] Release
  client/src/containers/Backend/Admin/Admin.module.scss
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
Labels: release

#1472 [STG-FRONT] Release
  client/src/components/Frontend/Dispositif/Dispositif.tsx
Labels: release

#1474 [STG-FRONT] Release
  server/src/locales/en/common.json
  server/src/locales/fa/common.json
  server/src/locales/ps/common.json
  server/src/locales/ru/common.json
  server/src/locales/uk/common.json
Labels: release

#1475 [STG-BACK] Release
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/containers/Backend/Admin/Admin.module.scss
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  server/src/locales/en/common.json
  server/src/locales/fa/common.json
  server/src/locales/ps/common.json
  server/src/locales/ru/common.json
  server/src/locales/uk/common.json
Labels: release

#1476 [PROD-FRONT] Release
  client/src/__tests__/__snapshots__/index.test.tsx.snap
  client/src/__tests__/__snapshots__/publier.test.tsx.snap
  client/src/__tests__/__snapshots__/traduire.test.tsx.snap
  client/src/assets/homepage/app-qr-code.png
  client/src/components/Content/ThemesGrid/ThemesGrid.module.scss
  client/src/components/Frontend/Dispositif/Dispositif.tsx
  client/src/components/Pages/homepage/CommunityCard/CommunityCard.module.scss
  client/src/components/Pages/homepage/CommunityCard/CommunityCard.tsx
  client/src/components/Pages/homepage/Sections/Community/Community.module.scss
  client/src/components/Pages/homepage/Sections/Community/Community.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/LanguageDropdown/LanguageDropdown.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/LanguageDropdown/LanguageDropdown.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/LanguageDropdown/index.ts
  client/src/components/Pages/homepage/Sections/MobileApp/MobileApp.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/MobileApp.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppSmsForm/MobileAppSmsForm.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppSmsForm/MobileAppSmsForm.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppSmsForm/index.ts
  client/src/components/Pages/homepage/Sections/NewContent/NewContent.tsx
  client/src/components/Pages/homepage/Sections/WhyAccordions/WhyAccordions.tsx
  client/src/components/Pages/staticPages/common/Accordion/Accordion.module.scss
  client/src/components/Pages/staticPages/common/Accordion/Accordion.tsx
  client/src/components/Pages/staticPages/common/AutoplayVideo/AutoplayVideo.module.scss
  client/src/components/Pages/staticPages/common/AutoplayVideo/AutoplayVideo.tsx
  client/src/components/Pages/staticPages/common/InlineLink/InlineLink.module.scss
  client/src/components/Pages/staticPages/common/StepContent/StepContent.module.scss
  client/src/components/Pages/staticPages/common/StepContent/StepContent.tsx
  client/src/components/Pages/staticPages/traduire/LanguageCard/LanguageCard.module.scss
  client/src/containers/Backend/Admin/Admin.module.scss
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  client/src/containers/Backend/Admin/AdminStructures/AdminStructures.tsx
  client/src/containers/Backend/Admin/AdminUsers/AdminUsers.tsx
  client/src/containers/Backend/Admin/Needs/Needs.tsx
  client/src/containers/Backend/Admin/sharedComponents/StyledAdmin.ts
  client/src/locales/fr/common.json
  client/src/pages/publier.tsx
  client/src/scss/components/staticPages.module.scss
  client/src/scss/mixins/_text.scss
  client/src/utils/API.ts
  server/src/connectors/twilio/sendSMS.ts
  server/src/controllers/miscellaneous/sms.js
  server/src/controllers/smsController.js
  server/src/locales/en/common.json
  server/src/locales/fa/common.json
  server/src/locales/fr/common.json
  server/src/locales/ps/common.json
  server/src/locales/ru/common.json
  server/src/locales/uk/common.json
  server/src/server.ts
  server/src/workflows/sms/downloadApp/downloadApp.test.ts
  server/src/workflows/sms/downloadApp/downloadApp.ts
  server/src/workflows/sms/downloadApp/index.ts
Labels: release
