Repository refugies-info/karfur, pull requests merged in 2023-01, with the labels that each got.

#1483 perf: :zap: add cache control for medias
  client/next.config.js
  client/src/scss/_fonts.scss
Labels: enhancement

#1487 refactor: cleanup and various bugfixes
  client/package-lock.json
  client/package.json
  client/src/assets/search_no_results.svg
  client/src/components/Frontend/Dispositif/LeftSideDispositif/LeftSideDispositif.tsx
  client/src/components/Layout/AppLoader/AppLoader.module.scss
  client/src/components/Layout/AppLoader/AppLoader.tsx
  client/src/components/Layout/Layout.module.scss
  client/src/components/Layout/Layout.scss
  client/src/components/Layout/Layout.tsx
  client/src/components/Modals/ShareContentOnMobileModal/ShareContentOnMobileModal.tsx
  client/src/components/Pages/dispositif/CardParagraphe/components/CardParagrapheComponents.tsx
  client/src/components/Pages/dispositif/SideTrad/ExpertSideTrad.js
  client/src/components/Pages/dispositif/SideTrad/SideTrad.js
  client/src/components/Pages/dispositif/function.ts
  client/src/components/Pages/homepage/CommunityCard/CommunityCard.module.scss
  client/src/components/Pages/homepage/Sections/Infos/Infos.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/MobileApp.module.scss
  client/src/components/Pages/recherche/ThemeDropdown/ThemeDropdown.tsx
  client/src/components/UI/AdvancedSearchBar/AdvancedSearchBar.scss
  client/src/components/UI/AdvancedSearchBar/AdvancedSearchBar.tsx
  client/src/components/UI/AdvancedSearchBar/NoResultPlaceholder.tsx
  client/src/data/synonym.ts
  client/src/scss/index.scss
  client/src/utils/API.ts
  server/src/controllers/miscellaneous/sms.js
  server/src/controllers/miscellaneousController.js
  server/src/controllers/smsController.js
  server/src/workflows/sms/contentLink/contentLink.test.ts
  server/src/workflows/sms/contentLink/contentLink.ts
  server/src/workflows/sms/contentLink/index.ts
Labels: enhancement

#1491 feat: :sparkles: delete a need with deleted associated content
  client/src/containers/Backend/Admin/Needs/NeedFormModal.tsx
  server/src/modules/dispositif/dispositif.repository.ts
  server/src/workflows/needs/deleteNeed/deleteNeed.test.ts
  server/src/workflows/needs/deleteNeed/deleteNeed.ts
Labels: enhancement

#1492 feat: :sparkles: allow an author to delete its content
  client/src/containers/Backend/UserContributions/UserContributions.tsx
  client/src/containers/Backend/UserContributions/__tests__/UserContributions.component.test.tsx
  client/src/containers/Backend/UserContributions/__tests__/__snapshots__/UserContributions.component.test.tsx.snap
  client/src/containers/Backend/UserContributions/__tests__/functions.test.ts
  client/src/containers/Backend/UserContributions/functions.ts
  server/src/libs/__tests__/checkAuthorizations.test.ts
  server/src/libs/checkAuthorizations.ts
  server/src/workflows/dispositif/updateDispositifStatus/updateDispositifStatus.test.ts
  server/src/workflows/dispositif/updateDispositifStatus/updateDispositifStatus.ts
  server/src/workflows/structure/updateStructure/updateStructure.ts
Labels: enhancement

#1493 feat: :sparkles: allow to choose structure responsable from content details modal
  client/src/components/UI/SearchBar/SearchBar.tsx
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  client/src/containers/Backend/Admin/AdminContenu/ContentDetailsModal/ContentDetailsModal.tsx
  client/src/containers/Backend/Admin/AdminStructures/AdminStructures.tsx
  client/src/containers/Backend/Admin/AdminUsers/AdminUsers.tsx
Labels: enhancement

#1494 feat: :recycle: use real links in backoffice to allow new tab click
  client/src/containers/Backend/Admin/AdminContenu/ContentDetailsModal/ContentDetailsModal.tsx
  client/src/containers/Backend/Admin/AdminStructures/StructureDetailsModal/StructureDetailsModal.tsx
  client/src/containers/Backend/Admin/sharedComponents/UserButton.tsx
  client/src/containers/Backend/UserContributions/UserContributions.tsx
  client/src/containers/Backend/UserContributions/__tests__/UserContributions.component.test.tsx
  client/src/containers/Backend/UserContributions/__tests__/__snapshots__/UserContributions.component.test.tsx.snap
  client/src/containers/Backend/UserContributions/components/SubComponents.tsx
  client/src/containers/Backend/UserContributions/components/UserContribTable.tsx
  client/src/containers/Backend/UserTranslation/__tests__/UserTranslation.component.test.tsx
  client/src/containers/Backend/UserTranslation/__tests__/__snapshots__/UserTranslation.component.test.tsx.snap
  client/src/containers/Backend/UserTranslation/components/TranslationAvancementTable.tsx
  client/src/containers/Backend/UserTranslation/components/TranslationsAvancement.tsx
Labels: enhancement

#1495 perf: :zap: do not prefetch pages
  client/src/components/Frontend/Dispositif/Sponsors/Sponsors.tsx
  client/src/components/Layout/Footer/FooterDSFR.tsx
  client/src/components/Modals/BookmarkedModal/BookmarkedModal.tsx
  client/src/components/Modals/LanguageModal/LanguageModal.tsx
  client/src/components/Navigation/Navbar/FrontendNavigation/FrontendNavigation.tsx
  client/src/components/Navigation/Navbar/NavbarItems/SubscribeToolItem/SubscribeToolItem.tsx
  client/src/components/Navigation/Navbar/NavbarItems/UserToolItem/UserToolItem.tsx
  client/src/components/Pages/annuaire/id/MiddleAnnuaireDetails.tsx
  client/src/components/Pages/annuaire/index/LetterSection.tsx
  client/src/components/Pages/homepage/CommunityCard/CommunityCard.tsx
  client/src/components/Pages/homepage/Sections/HelpUs/HelpUs.tsx
  client/src/components/Pages/qui-sommes-nous/Contribution.tsx
  client/src/components/Pages/recherche/NotDeployedBanner/NotDeployedBanner.tsx
  client/src/components/UI/DemarcheCard/DemarcheCard.tsx
  client/src/components/UI/DispositifCard/DispositifCard.tsx
  client/src/containers/Backend/UserStructure/__tests__/__snapshots__/UserStructure.test.tsx.snap
  client/src/containers/Backend/UserStructure/components/UserStructureDetails.tsx
  client/src/pages/mentions-legales.tsx
  client/src/pages/plan-du-site.tsx
  client/src/pages/politique-de-confidentialite.tsx
Labels: enhancement

#1496 perf: :zap: minimize dom size on annuaire
  client/package-lock.json
  client/package.json
  client/src/components/Layout/Layout.module.scss
  client/src/components/Pages/annuaire/index/LetterSection.module.scss
  client/src/components/Pages/annuaire/index/LetterSection.tsx
Labels: bug

#1499 fix: :bug: prevent the use of the same password when reset
  client/src/locales/fr/common.json
  client/src/pages/reset.tsx
  server/src/workflows/users/login/login.exceptions.manager.ts
  server/src/workflows/users/setNewPassword/setNewPassword.test.ts
  server/src/workflows/users/setNewPassword/setNewPassword.ts
Labels: bug

#1500 fix: :bug: fix need translation status
  server/src/workflows/needs/saveNeed/saveNeed.test.ts
  server/src/workflows/needs/saveNeed/saveNeed.ts
Labels: bug

#1501 feat: :sparkles: export translated titles in airtable
  client/src/containers/Backend/Admin/AdminContenu/AdminContenu.tsx
  server/src/workflows/dispositif/exportFiches/exportFiches.ts
Labels: enhancement

#1502 feat: password strength
  client/src/components/Pages/register/PasswordField/PasswordField.module.scss
  client/src/components/Pages/register/PasswordField/PasswordField.tsx
  client/src/components/User/PasswordStrength/PasswordStrength.module.scss
  client/src/components/User/PasswordStrength/PasswordStrength.tsx
  client/src/components/User/PasswordStrength/index.ts
  client/src/containers/Backend/UserProfile/UserProfile.tsx
  client/src/containers/Backend/UserProfile/__test__/UserProfile.component.test.tsx
  client/src/containers/Backend/UserProfile/__test__/__snapshots__/UserProfile.component.test.tsx.snap
  client/src/containers/Backend/UserProfile/components/PasswordField.tsx
  client/src/lib/index.test.ts
  client/src/lib/index.ts
  client/src/lib/validatePassword.ts
  client/src/locales/ar/common.json
  client/src/locales/ar/unused.json
  client/src/locales/en/common.json
  client/src/locales/en/unused.json
  client/src/locales/fa/common.json
  client/src/locales/fa/unused.json
  client/src/locales/fr/common.json
  client/src/locales/fr/unused.json
  client/src/locales/ps/common.json
  client/src/locales/ps/unused.json
  client/src/locales/ru/common.json
  client/src/locales/ru/unused.json
  client/src/locales/ti/common.json
  client/src/locales/ti/unused.json
  client/src/pages/reset.tsx
  client/src/scss/_colors.scss
  server/src/libs/__tests__/computePasswordStrengthScore.test.ts
  server/src/libs/__tests__/validatePassword.test.ts
  server/src/libs/computePasswordStrengthScore.ts
  server/src/libs/validatePassword.ts
  server/src/modules/users/register.ts
  server/src/workflows/users/changePassword/changePassword.test.ts
  server/src/workflows/users/changePassword/changePassword.ts
  server/src/workflows/users/setNewPassword/setNewPassword.test.ts
  server/src/workflows/users/setNewPassword/setNewPassword.ts
Labels: enhancement

#1506 perf: :zap: lazyload scripts
  client/src/pages/_app.tsx
Labels: enhancement

#1508 [STG-FRONT] Release
  client/src/containers/Backend/Admin/Logs/LogLine.module.scss
  client/src/pages/_app.tsx
Labels: release

#1509 fix: :bug: prevent same password on user profile
  client/src/containers/Backend/UserProfile/UserProfile.tsx
  server/src/controllers/userController.js
  server/src/workflows/users/changePassword/changePassword.test.ts
  server/src/workflows/users/changePassword/changePassword.ts
  server/src/workflows/users/changePassword/index.ts
Labels: bug

#1513 [STG-FRONT] Release
  client/src/components/Frontend/Dispositif/Sponsors/Sponsors.module.scss
  client/src/components/Frontend/Dispositif/Sponsors/Sponsors.tsx
  client/src/components/UI/SearchBar/SearchBar.scss
  client/src/components/UI/SearchBar/SearchBar.tsx
  client/src/components/UI/SearchStructures/SearchStructureResult/SearchStructureResult.tsx
  client/src/components/UI/SearchStructures/SearchStructureResult/index.ts
  client/src/components/UI/SearchStructures/SearchStructures.module.scss
  client/src/components/UI/SearchStructures/SearchStructures.tsx
  client/src/components/UI/SearchStructures/index.ts
  client/src/components/UI/index.ts
  client/src/components/index.ts
  client/src/containers/Backend/Admin/AdminContenu/ChangeStructureModale/ChangeStructureModale.tsx
  client/src/containers/Backend/Admin/AdminStructures/AdminStructures.tsx
  client/src/containers/Backend/Admin/AdminStructures/NewStructureModal/NewStructureModal.tsx
  client/src/containers/Backend/Admin/AdminStructures/NewStructureModal/index.ts
  client/src/containers/Backend/Admin/AdminStructures/StructureDetailsModal/StructureDetailsModal.tsx
  client/src/types/interface.d.ts
Labels: release

#1512 style: :lipstick: various style fix on static pages
  client/jest/setup.js
  client/src/__tests__/__snapshots__/index.test.tsx.snap
  client/src/__tests__/__snapshots__/publier.test.tsx.snap
  client/src/__tests__/__snapshots__/traduire.test.tsx.snap
  client/src/components/Pages/homepage/CommunityCard/CommunityCard.module.scss
  client/src/components/Pages/homepage/Sections/HelpUs/HelpUs.module.scss
  client/src/components/Pages/homepage/Sections/Hero/Hero.module.scss
  client/src/components/Pages/homepage/Sections/Infos/Infos.module.scss
  client/src/components/Pages/homepage/Sections/Infos/Infos.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/LanguageDropdown/LanguageDropdown.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/LanguageDropdown/LanguageDropdown.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileApp.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppIllu/MobileAppIllu.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppIllu/MobileAppIllu.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppSmsForm/MobileAppSmsForm.module.scss
  client/src/components/Pages/homepage/Sections/NewContent/NewContent.tsx
  client/src/components/Pages/recherche/CardSlider/CardSlider.module.scss
  client/src/components/Pages/staticPages/common/AutoplayVideo/AutoplayVideo.tsx
  client/src/components/Pages/staticPages/common/HeroArrow/HeroArrow.module.scss
  client/src/components/Pages/staticPages/common/HeroArrow/HeroArrow.tsx
  client/src/components/Pages/staticPages/common/SecondaryNavbar/SecondaryNavbar.tsx
  client/src/components/Pages/staticPages/traduire/LanguageCard/LanguageCard.module.scss
  client/src/components/Pages/staticPages/traduire/LanguageCard/LanguageCard.tsx
  client/src/components/UI/DispositifCard/DispositifCard.module.scss
  client/src/components/UI/Warning/Warning.module.scss
  client/src/components/UI/Warning/Warning.tsx
  client/src/containers/Backend/UserContributions/__tests__/__snapshots__/UserContributions.component.test.tsx.snap
  client/src/containers/Backend/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  client/src/containers/Backend/UserStructure/__tests__/__snapshots__/UserStructure.test.tsx.snap
  client/src/lib/smoothScroll.ts
  client/src/locales/fr/common.json
  client/src/pages/publier.tsx
  client/src/pages/traduire.tsx
  client/src/scss/components/staticPages.module.scss
Labels: enhancement

#1514 [STG-FRONT] Release
  client/jest/setup.js
  client/src/__tests__/__snapshots__/index.test.tsx.snap
  client/src/__tests__/__snapshots__/publier.test.tsx.snap
  client/src/__tests__/__snapshots__/traduire.test.tsx.snap
  client/src/components/Pages/homepage/CommunityCard/CommunityCard.module.scss
  client/src/components/Pages/homepage/Sections/HelpUs/HelpUs.module.scss
  client/src/components/Pages/homepage/Sections/Hero/Hero.module.scss
  client/src/components/Pages/homepage/Sections/Infos/Infos.module.scss
  client/src/components/Pages/homepage/Sections/Infos/Infos.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/LanguageDropdown/LanguageDropdown.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/LanguageDropdown/LanguageDropdown.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileApp.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppIllu/MobileAppIllu.module.scss
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppIllu/MobileAppIllu.tsx
  client/src/components/Pages/homepage/Sections/MobileApp/MobileAppSmsForm/MobileAppSmsForm.module.scss
  client/src/components/Pages/homepage/Sections/NewContent/NewContent.tsx
  client/src/components/Pages/recherche/CardSlider/CardSlider.module.scss
  client/src/components/Pages/staticPages/common/AutoplayVideo/AutoplayVideo.tsx
  client/src/components/Pages/staticPages/common/HeroArrow/HeroArrow.module.scss
  client/src/components/Pages/staticPages/common/HeroArrow/HeroArrow.tsx
  client/src/components/Pages/staticPages/common/SecondaryNavbar/SecondaryNavbar.tsx
  client/src/components/Pages/staticPages/traduire/LanguageCard/LanguageCard.module.scss
  client/src/components/Pages/staticPages/traduire/LanguageCard/LanguageCard.tsx
  client/src/components/UI/DispositifCard/DispositifCard.module.scss
  client/src/components/UI/Warning/Warning.module.scss
  client/src/components/UI/Warning/Warning.tsx
  client/src/containers/Backend/UserContributions/__tests__/__snapshots__/UserContributions.component.test.tsx.snap
  client/src/containers/Backend/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  client/src/containers/Backend/UserStructure/__tests__/__snapshots__/UserStructure.test.tsx.snap
  client/src/lib/smoothScroll.ts
  client/src/locales/fr/common.json
  client/src/pages/publier.tsx
  client/src/pages/traduire.tsx
  client/src/scss/components/staticPages.module.scss
Labels: release

#1516 docs: :lipstick: search inputs mobile design
  client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.mobile.tsx
  client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.tsx
  client/src/components/Pages/recherche/SearchHeader/SearchHeader.mobile.tsx
  client/src/components/Pages/recherche/SearchHeader/SearchHeader.tsx
  client/src/scss/components/searchHeader.module.scss
Labels: bug

#1515 feat: :sparkles: Optimisation Algolia
  client/src/containers/Backend/Admin/AdminContenu/ContentDetailsModal/ContentDetailsModal.tsx
  client/src/types/interface.d.ts
  client/src/utils/API.ts
  server/src/controllers/dispositifController.js
  server/src/libs/__tests__/formatForAlgolia.test.ts
  server/src/libs/formatForAlgolia.ts
  server/src/modules/dispositif/dispositif.repository.ts
  server/src/schema/schemaDispositif.ts
  server/src/types/interface.d.ts
  server/src/workflows/dispositif/getAllDispositifs/getAllDispositifs.test.ts
  server/src/workflows/dispositif/getAllDispositifs/getAllDispositifs.ts
  server/src/workflows/dispositif/updateDispositif/index.ts
  server/src/workflows/dispositif/updateDispositif/updateDispositif.test.ts
  server/src/workflows/dispositif/updateDispositif/updateDispositif.ts
  server/src/workflows/search/updateIndex/updateIndex.ts
Labels: enhancement

#1518 [STG-FRONT] Release
  client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.mobile.tsx
  client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.tsx
  client/src/components/Pages/recherche/SearchHeader/SearchHeader.mobile.tsx
  client/src/components/Pages/recherche/SearchHeader/SearchHeader.tsx
  client/src/containers/Backend/Admin/AdminContenu/ContentDetailsModal/ContentDetailsModal.tsx
  client/src/scss/components/searchHeader.module.scss
  client/src/types/interface.d.ts
  client/src/utils/API.ts
  server/src/controllers/dispositifController.js
  server/src/libs/__tests__/formatForAlgolia.test.ts
  server/src/libs/formatForAlgolia.ts
  server/src/modules/dispositif/dispositif.repository.ts
  server/src/schema/schemaDispositif.ts
  server/src/types/interface.d.ts
  server/src/workflows/dispositif/getAllDispositifs/getAllDispositifs.test.ts
  server/src/workflows/dispositif/getAllDispositifs/getAllDispositifs.ts
  server/src/workflows/dispositif/updateDispositif/index.ts
  server/src/workflows/dispositif/updateDispositif/updateDispositif.test.ts
  server/src/workflows/dispositif/updateDispositif/updateDispositif.ts
  server/src/workflows/search/updateIndex/updateIndex.ts
Labels: release

#1520 [STG-BACK] Release
  server/src/locales/ar/common.json
Labels: release

#1524 [STG-FRONT] Release
  client/src/pages/recherche.tsx
  server/src/locales/ar/common.json
Labels: release

#1525 [PROD-FRONT] Release
  client/src/pages/recherche.tsx
  server/src/locales/ar/common.json
Labels: release

#1528 [STG-FRONT] Release
  client/src/containers/Backend/Admin/AdminUsers/AdminUsers.tsx
Labels: release

#1529 [PROD-FRONT] Release
  client/src/containers/Backend/Admin/AdminUsers/AdminUsers.tsx
Labels: release
