Repository refugies-info/karfur, pull requests merged in 2024-11, with the labels that each got.

#2386 [STG-BACK] Release
  apps/client/src/components/Pages/recherche/LocationMenu/LocationMenu.tsx
  apps/client/src/hooks/useIsSticky.ts
  apps/server/src/modules/dispositif/dispositif.repository.ts
Labels: release

#2387 [STG-FRONT] Release
  apps/client/src/components/Pages/recherche/LocationMenu/LocationMenu.tsx
  apps/client/src/hooks/useIsSticky.ts
  apps/server/src/modules/dispositif/dispositif.repository.ts
Labels: release

#2390 Fix: variable tuiles sizes on grid system
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.module.scss
Labels: enhancement

#2392 [STG-BACK] Release
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.module.scss
Labels: release

#2394 [STG-FRONT] Release
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.module.scss
Labels: release

#2398 [STG-BACK] Release
  .github/workflows/deploy_mobile_staging.yml
  .github/workflows/migrate_production.yaml
  .github/workflows/migrate_staging.yaml
  migrations/cli.ts
  package.json
  yarn.lock
Labels: release

#2400 [STG-BACK] Release
  migrations/cli.ts
  package.json
Labels: release

#2401 [PROD-BACK] Release
  migrations/cli.ts
  package.json
Labels: release

#2389 Feature : Advanced card filtering
  apps/client/src/lib/recherche/filterContents.ts
  apps/client/src/lib/recherche/queryContents.ts
Labels: enhancement

#2402 Fix: 🐛 Broken Sort function
  apps/client/src/lib/recherche/queryContents.ts
Labels: bug

#2404 [STG-BACK] Release
  apps/client/src/components/Layout/AppLoader/AppLoader.module.scss
  apps/client/src/components/Layout/AppLoader/AppLoader.tsx
  apps/client/src/components/Layout/AppLoader/index.ts
  apps/client/src/components/Layout/Layout.tsx
  apps/client/src/components/Pages/recherche/ResultsFilter/ResultsFilter.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/hooks.tsx
  apps/client/src/lib/recherche/filterContents.ts
  apps/client/src/lib/recherche/queryContents.ts
  apps/client/src/pages/_app.tsx
  apps/client/src/services/LoadingStatus/loadingStatus.actions.ts
  apps/client/src/services/SearchResults/searchResults.reducer.ts
Labels: release

#2405 [STG-FRONT] Release
  .github/workflows/deploy_mobile_staging.yml
  .github/workflows/migrate_production.yaml
  .github/workflows/migrate_staging.yaml
  apps/client/src/components/Layout/AppLoader/AppLoader.module.scss
  apps/client/src/components/Layout/AppLoader/AppLoader.tsx
  apps/client/src/components/Layout/AppLoader/index.ts
  apps/client/src/components/Layout/Layout.tsx
  apps/client/src/components/Pages/recherche/ResultsFilter/ResultsFilter.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/hooks.tsx
  apps/client/src/lib/recherche/filterContents.ts
  apps/client/src/lib/recherche/queryContents.ts
  apps/client/src/pages/_app.tsx
  apps/client/src/services/LoadingStatus/loadingStatus.actions.ts
  apps/client/src/services/SearchResults/searchResults.reducer.ts
  migrations/cli.ts
  package.json
  yarn.lock
Labels: release

#2408 [STG-MOBILE] Release
  .github/workflows/deploy_mobile_prod.yml
  .github/workflows/deploy_mobile_staging.yml
  package.json
Labels: release

#2410 [STG-MOBILE] Release
  .github/workflows/build_mobile_prod.yml
  .github/workflows/build_mobile_staging.yml
  .github/workflows/migrate_production.yaml
  .github/workflows/migrate_staging.yaml
  apps/mobile/app.config.js
Labels: release

#2413 [STG-MOBILE] Release
  .github/workflows/build_mobile_prod.yml
  .github/workflows/build_mobile_staging.yml
  apps/mobile/app.config.js
Labels: release

#2353 feat: :sparkles: new archived status
  apps/client/src/components/Backend/screens/Admin/AdminContenu/data.ts
  apps/client/src/components/Pages/dispositif/Status/functions.ts
  apps/server/src/connectors/sendgrid/templatesIds.ts
  apps/server/src/modules/mail/data.ts
  apps/server/src/modules/mail/mail.service.ts
  apps/server/src/modules/mail/sendMailWhenDispositifArchived.ts
  apps/server/src/workflows/dispositif/updateDispositifStatus/updateDispositifStatus.ts
  packages/api-types/src/generics.ts
Labels: enhancement

#2391 fix: :bug: prevent publication when already published and no change
  .vscode/extensions.json
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/CustomNavbarEdit.tsx
  apps/server/src/workflows/dispositif/publishDispositif/publishDispositif.ts
Labels: bug

#2419 [STG-MOBILE] Release
  .github/workflows/build_mobile_prod.yml
  .github/workflows/build_mobile_staging.yml
  .gitignore
  .vscode/extensions.json
  apps/client/src/components/Backend/screens/Admin/AdminContenu/data.ts
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/CustomNavbarEdit.tsx
  apps/client/src/components/Pages/dispositif/Status/functions.ts
  apps/mobile/.gitignore
  apps/mobile/app.config.js
  apps/mobile/eas.json
  apps/server/src/connectors/sendgrid/templatesIds.ts
  apps/server/src/modules/mail/data.ts
  apps/server/src/modules/mail/mail.service.ts
  apps/server/src/modules/mail/sendMailWhenDispositifArchived.ts
  apps/server/src/workflows/dispositif/publishDispositif/publishDispositif.ts
  apps/server/src/workflows/dispositif/updateDispositifStatus/updateDispositifStatus.ts
  documentation/mobile/README.md
  package.json
  packages/api-types/src/generics.ts
Labels: release

#2421 [STG-MOBILE] Release
  .github/workflows/build_mobile_staging.yml
Labels: release

#2423 [STG-MOBILE] Release
  .github/workflows/build_mobile_prod.yml
  .github/workflows/build_mobile_staging.yml
Labels: release

#2426 [STG-MOBILE] Release
  .github/workflows/build_mobile_prod.yml
  .github/workflows/build_mobile_staging.yml
Labels: release

#2427 [PROD-MOBILE] Release
  .github/workflows/build_mobile_prod.yml
  .github/workflows/build_mobile_staging.yml
  .github/workflows/migrate_production.yaml
  .github/workflows/migrate_staging.yaml
  .gitignore
  .vscode/extensions.json
  apps/client/src/components/Backend/screens/Admin/AdminContenu/data.ts
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/CustomNavbarEdit.tsx
  apps/client/src/components/Pages/dispositif/Status/functions.ts
  apps/mobile/.gitignore
  apps/mobile/app.config.js
  apps/mobile/eas.json
  apps/server/src/connectors/sendgrid/templatesIds.ts
  apps/server/src/modules/mail/data.ts
  apps/server/src/modules/mail/mail.service.ts
  apps/server/src/modules/mail/sendMailWhenDispositifArchived.ts
  apps/server/src/workflows/dispositif/publishDispositif/publishDispositif.ts
  apps/server/src/workflows/dispositif/updateDispositifStatus/updateDispositifStatus.ts
  documentation/mobile/README.md
  package.json
  packages/api-types/src/generics.ts
Labels: release

#2430 [STG-MOBILE] Release
  .github/workflows/build_mobile_prod.yml
Labels: release

#2431 [PROD-MOBILE] Release
  .github/workflows/build_mobile_prod.yml
Labels: release

#2434 [STG-MOBILE] Release
  .github/workflows/build_mobile_prod.yml
  .github/workflows/build_mobile_staging.yml
  apps/mobile/eas.json
  apps/mobile/src/components/StreamlineIcon.tsx
Labels: release

#2436 [PROD-BACK] Release
  apps/client/src/components/Layout/AppLoader/AppLoader.module.scss
  apps/client/src/components/Layout/AppLoader/AppLoader.tsx
  apps/client/src/components/Layout/AppLoader/index.ts
  apps/client/src/components/Layout/Layout.tsx
  apps/client/src/components/Pages/recherche/ResultsFilter/ResultsFilter.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/hooks.tsx
  apps/client/src/lib/recherche/filterContents.ts
  apps/client/src/lib/recherche/queryContents.ts
  apps/client/src/pages/_app.tsx
  apps/client/src/services/LoadingStatus/loadingStatus.actions.ts
  apps/client/src/services/SearchResults/searchResults.reducer.ts
Labels: release

#2455 fix(server): :bug: prevent error when getRegionName parameter undefined
  apps/server/src/modules/dispositif/dispositif.adapter.ts
Labels: bug

#2406 Accessibility - Search page
  apps/client/src/__tests__/__snapshots__/index.test.tsx.snap
  apps/client/src/__tests__/__snapshots__/recherche.test.tsx.snap
  apps/client/src/components/Backend/screens/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  apps/client/src/components/Pages/recherche/LocationMenu/CommonPlaceMenuItem.tsx
  apps/client/src/components/Pages/recherche/LocationMenu/SearchMenuItem.module.css
  apps/client/src/components/Pages/recherche/LocationMenu/SearchMenuItem.tsx
  apps/client/src/components/Pages/recherche/ResultsFilter/ResultsFilter.module.scss
  apps/client/src/components/Pages/recherche/ResultsFilter/ResultsFilter.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/DropdownButton/DropdownButton.module.scss
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/Filter.module.scss
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/Filter.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/MenuLayouts/DialogMenuLayout.module.scss
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/MenuLayouts/DropDownMenuContext.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/MenuLayouts/DropDownMenuLayout.module.scss
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/MenuLayouts/DropDownMenuLayout.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/MenuLayouts/index.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filters.module.scss
  apps/client/src/components/Pages/recherche/SearchHeader/Filters.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/SearchHeader.module.scss
  apps/client/src/components/Pages/recherche/SearchHeader/SearchHeader.tsx
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.module.scss
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.tsx
  apps/client/src/components/Pages/recherche/ThemeMenu/NeedItem.module.css
  apps/client/src/components/Pages/recherche/ThemeMenu/NeedItem.tsx
  apps/client/src/components/Pages/recherche/ThemeMenu/Needs.tsx
  apps/client/src/components/Pages/recherche/ThemeMenu/ThemeItem.module.css
  apps/client/src/components/Pages/recherche/ThemeMenu/ThemeMenu.module.scss
  apps/client/src/components/Pages/recherche/ThemeMenu/ThemeMenu.tsx
  apps/client/src/components/Pages/recherche/ThemeMenu/Themes.module.css
  apps/client/src/components/Pages/recherche/ThemeMenu/Themes.tsx
  apps/client/src/components/UI/Checkbox/Checkbox.module.css
  apps/client/src/components/UI/Checkbox/Checkbox.tsx
  apps/client/src/components/UI/Checkbox/CheckboxIcon.module.css
  apps/client/src/components/UI/Checkbox/CheckboxIcon.tsx
  apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
  apps/client/src/components/UI/FavoriteButton/FavoriteButton.module.scss
  apps/client/src/components/UI/FavoriteButton/FavoriteButton.tsx
  apps/client/src/components/UI/SearchButton/SearchButton.module.css
  apps/client/src/components/UI/SearchButton/SearchButton.tsx
  apps/client/src/hooks/useStyleDisabled.ts
  apps/client/src/hooks/useWindowSize.ts
  apps/client/src/locales/fr/common.json
  apps/client/src/scss/_common.scss
  apps/client/src/scss/_variables.scss
  apps/client/src/scss/components/contentCard.module.scss
  apps/client/src/scss/mixins/_responsive.scss
Labels: accessibility

#2469 feat(client): :sparkles: add new buttons on NewProfile modale
  apps/client/src/components/Modals/NewProfileModal/NewProfileModal.module.scss
  apps/client/src/components/Modals/NewProfileModal/NewProfileModal.tsx
Labels: enhancement
