Repository refugies-info/karfur, pull requests merged in 2024-09, with the labels that each got.

#2256 feat: :sparkles: add theme images
  apps/client/src/__fixtures__/activeThemes.ts
  apps/client/src/__tests__/__snapshots__/index.test.tsx.snap
  apps/client/src/components/Backend/screens/Admin/Needs/ThemeFormModal.tsx
  apps/client/src/components/Backend/screens/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  apps/client/src/hooks/useCardImage.ts
  apps/client/src/lib/getTheme.ts
  apps/mobile/src/jest/__fixtures__/selectedContent.ts
  apps/mobile/src/jest/__fixtures__/themes.ts
  apps/mobile/src/screens/SearchTab/__tests__/__snapshots__/SearchResultsScreen.test.tsx.snap
  apps/mobile/src/screens/SearchTab/__tests__/__snapshots__/SearchScreen.test.tsx.snap
  apps/mobile/src/screens/__tests__/__snapshots__/ContentScreen.test.tsx.snap
  apps/server/src/__fixtures__/theme.ts
  apps/server/src/typegoose/Theme.ts
  migrations/1725277837812_ThemeAddImages.ts
  packages/api-types/src/generics.ts
  packages/api-types/src/modules/theme.ts
Labels: enhancement

#2261 RI-16 : moteur de redaction
  apps/client/src/__fixtures__/getDispositifs.ts
  apps/client/src/__tests__/__snapshots__/index.test.tsx.snap
  apps/client/src/components/Backend/screens/UserContributions/__tests__/functions.test.ts
  apps/client/src/components/Backend/screens/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  apps/client/src/components/Pages/dispositif/Edition/LeftSidebarEdition/LeftSidebarEdition.tsx
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalDemarcheAdministration/ModalDemarcheAdministration.module.scss
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalDemarcheAdministration/ModalDemarcheAdministration.tsx
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalDemarcheAdministration/data.ts
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalDemarcheAdministration/index.ts
  apps/client/src/components/Pages/dispositif/Edition/Modals/index.ts
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/CardDemarcheAdministration.module.scss
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/CardDemarcheAdministration.tsx
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/index.ts
  apps/client/src/components/UI/DemarcheCard/DemarcheCard.tsx
  apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
  apps/client/src/lib/dispositifForm.ts
  apps/client/src/utils/API.ts
  apps/client/src/utils/pageContext.ts
  apps/server/src/__fixtures__/demarche.ts
  apps/server/src/libs/__tests__/wordCounter.test.ts
  apps/server/src/modules/dispositif/dispositif.repository.ts
  apps/server/src/modules/dispositif/dispositif.service.ts
  apps/server/src/typegoose/Dispositif.ts
  apps/server/src/typegoose/Traductions.test.ts
  apps/server/src/workflows/dispositif/createDispositif/createDispositif.ts
  apps/server/src/workflows/dispositif/getContentById/getContentById.ts
  apps/server/src/workflows/dispositif/updateDispositif/updateDispositif.ts
  packages/api-types/src/generics.ts
  packages/api-types/src/modules/dispositif.ts
  packages/api-types/src/modules/translations.ts
Labels: enhancement

#2266 fix(client): :bug: use dsfr for missing colors
  apps/client/src/components/Pages/dispositif/ActionButtons/SendSMSModal/SendSMSModal.tsx
  apps/client/src/components/Pages/dispositif/Breadcrumb/Breadcrumb.tsx
  apps/client/src/components/Pages/dispositif/Edition/AccordionsEdit/AccordionItem/AccordionItem.tsx
  apps/client/src/components/Pages/dispositif/Edition/AddContentButton/AddContentButton.tsx
  apps/client/src/components/Pages/dispositif/Edition/ChoiceButton/ChoiceButton.tsx
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/CustomNavbarEdit.tsx
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/PublishModal/CompleteContent/PublicationSteps/PublicationSteps.tsx
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/QuitModal/QuitModal.tsx
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarTranslate/QuitModal/QuitModal.tsx
  apps/client/src/components/Pages/dispositif/Edition/LeftSidebarEdition/LeftSidebarEdition.tsx
  apps/client/src/components/Pages/dispositif/Edition/LogoInput/LogoInput.tsx
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalAbstract/ModalAbstract.tsx
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalMainSponsor/ThanksMessage/ThanksMessage.tsx
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalMainSponsor/data.tsx
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalThemes/ModalThemes.tsx
  apps/client/src/components/Pages/dispositif/Edition/Modals/components/RemovableItem/RemovableItem.tsx
  apps/client/src/components/Pages/dispositif/Input/Input.tsx
  apps/client/src/components/Pages/dispositif/LangueSelectList/LangueSelectList.tsx
  apps/client/src/components/Pages/dispositif/Map/PopupContent/PopupContent.tsx
  apps/client/src/components/Pages/dispositif/Metadatas/BaseCard/BaseCard.tsx
  apps/client/src/components/Pages/dispositif/StructureReceiveDispositif/StructureReceiveDispositif.tsx
  apps/client/src/components/Pages/dispositif/Translation/SectionTitleAbstract/SectionTitleAbstract.tsx
  apps/client/src/components/Pages/dispositif/Translation/TranslationInput/TranslationEditField/TranslationEditField.tsx
  apps/client/src/components/UI/Button/Button.tsx
  apps/client/src/components/UI/Camembert/Camembert.tsx
  apps/client/src/components/UI/FRLink/FRLink.tsx
  apps/client/src/components/UI/Toast/Toast.tsx
Labels: bug

#2274 fix(mobile): :bug: fix references to translation files on app
  apps/mobile/src/config/i18n.ts
  apps/mobile/src/translations/scripts/convertCsvToJson.js
  apps/mobile/src/translations/scripts/convertCsvToJsonFr.js
  apps/mobile/src/translations/scripts/convertJsonToCsv.js
  apps/mobile/src/translations/scripts/convertJsonToCsvFr.js
Labels: bug

#2273 fix(client): :lipstick: update demo card
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalAbstract/ModalAbstract.module.scss
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalAbstract/ModalAbstract.tsx
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalAbstract/functions.ts
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalAbstract/useSponsorData.ts
  apps/client/src/components/UI/DemarcheCard/DemarcheCard.tsx
  apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
  apps/client/src/scss/components/contentCard.module.scss
Labels: enhancement

#2284 [STG-BACK] Release
  apps/client/next-env.d.ts
  apps/client/package.json
  apps/mobile/package.json
  apps/mobile/src/hooks/useApi.ts
  apps/mobile/src/types/react-native-axios.d.ts
  apps/mobile/src/utils/ConfigAPI.ts
  apps/server/package.json
  apps/server/src/workflows/structure/getAllStructures/getAllStructures.ts
  package.json
  yarn.lock
Labels: release

#2283 [STG-FRONT] Release
  apps/client/next-env.d.ts
  apps/client/package.json
  apps/mobile/package.json
  apps/mobile/src/hooks/useApi.ts
  apps/mobile/src/types/react-native-axios.d.ts
  apps/mobile/src/utils/ConfigAPI.ts
  apps/server/package.json
  apps/server/src/workflows/structure/getAllStructures/getAllStructures.ts
  package.json
  yarn.lock
Labels: release

#2288 [STG-BACK] Release
  apps/client/cloudbuild.yaml
  apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
Labels: release

#2268 feat(client): :sparkles: add administrationName to translation form
  apps/client/src/components/Content/DispositifTranslate/DispositifTranslate.tsx
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/PublishModal/MissingContent/MissingContent.tsx
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/PublishModal/MissingContent/data.ts
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/functions.ts
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/MissingSteps/data.ts
  apps/client/src/hooks/dispositif/useDispositifTranslation/progressFunctions.ts
  apps/client/src/hooks/dispositif/useDispositifTranslation/useDispositifTranslation.ts
  packages/api-types/src/modules/translations.ts
Labels: enhancement

#2291 fix: :bug: fix show right languages for draft versions
  apps/client/src/pages/demarche/[id]/translate.tsx
  apps/client/src/pages/dispositif/[id]/translate.tsx
  apps/server/src/workflows/dispositif/getContentById/getContentById.ts
Labels: bug

#2292 fix: :bug: fix dispo create bugs for administration name and logo
  apps/client/src/components/Pages/dispositif/Edition/LeftSidebarEdition/LeftSidebarEdition.tsx
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/CardDemarcheAdministration.module.scss
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/CardDemarcheAdministration.tsx
  apps/server/src/modules/dispositif/dispositif.service.ts
Labels: bug

#2293 fix(client): :bug: fix accordions disappearing in react strict mode
  apps/client/src/components/Pages/dispositif/Edition/AccordionsEdit/AccordionItem/AccordionItem.tsx
Labels: bug
