Repository refugies-info/karfur, pull requests merged in 2024-12, with the labels that each got.

#2497 [PROD-BACK] [HOTFIX] Release
  apps/server/package.json
  apps/server/tsoa.json
  packages/api-types/src/modules/translations.ts
  yarn.lock
Labels: release

#2495 fix(server): :bug: fix translation not saving with tsoa@6
  apps/server/package.json
  apps/server/tsoa.json
  packages/api-types/src/modules/translations.ts
  yarn.lock
Labels: bug

#2503 fix(mobile): :bug: fix white icons in TagButton and set appImage on all TagButtons
  apps/mobile/package.json
  apps/mobile/src/components/Explorer/CarousselCard.tsx
  apps/mobile/src/components/Explorer/TagButton.tsx
  apps/mobile/src/components/Explorer/TagImage.tsx
  apps/mobile/src/components/Search/SearchContentSummary.tsx
  apps/mobile/src/components/Search/SearchSuggestions.tsx
  apps/mobile/src/screens/SearchTab/__tests__/__snapshots__/SearchResultsScreen.test.tsx.snap
  apps/mobile/src/screens/SearchTab/__tests__/__snapshots__/SearchScreen.test.tsx.snap
  apps/mobile/src/screens/__tests__/__snapshots__/ContentScreen.test.tsx.snap
  pnpm-lock.yaml
Labels: bug

#2505 Feature(accessibility): add the skip links navigation
  apps/client/src/components/Layout/Layout.tsx
  apps/client/src/components/UI/SkipLinksNavigation/SkipLinksNavigation.tsx
  apps/client/src/locales/fr/common.json
  apps/client/src/pages/_document.tsx
Labels: accessibility

#2512 [STG-BACK] Release
  apps/client/Dockerfile
  apps/client/cloudbuild.yaml
  apps/server/Dockerfile
Labels: release

#2514 [STG-BACK] Release
  apps/client/Dockerfile
  apps/server/Dockerfile
Labels: release

#2516 [STG-BACK] Release
  apps/server/package.json
  pnpm-lock.yaml
Labels: release

#2518 [STG-BACK] Release
  apps/client/src/__fixtures__/reduxStore.ts
  apps/client/src/components/Backend/screens/UserFavorites/UserFavorites.tsx
  apps/client/src/components/Layout/Layout.tsx
  apps/client/src/hooks/useFavorites.ts
  apps/client/src/services/UserFavoritesInLocale/UserFavoritesInLocale.reducer.ts
  apps/client/src/services/UserFavoritesInLocale/UserFavoritesInLocale.selectors.ts
Labels: release

#2519 [STG-FRONT] Release
  apps/client/src/__fixtures__/reduxStore.ts
  apps/client/src/components/Backend/screens/UserFavorites/UserFavorites.tsx
  apps/client/src/components/Layout/Layout.tsx
  apps/client/src/hooks/useFavorites.ts
  apps/client/src/services/UserFavoritesInLocale/UserFavoritesInLocale.reducer.ts
  apps/client/src/services/UserFavoritesInLocale/UserFavoritesInLocale.selectors.ts
Labels: release

#2500 fix(server): :bug: remove administrationName from added sections if null
  apps/server/src/typegoose/Traductions.test.ts
  apps/server/src/typegoose/Traductions.ts
  migrations/1733826190794_RemoveStuckedToReview.ts
Labels: bug

#2521 [STG-BACK] Release
  apps/server/src/typegoose/Traductions.test.ts
  apps/server/src/typegoose/Traductions.ts
  migrations/1733826190794_RemoveStuckedToReview.ts
Labels: release

#2522 [STG-FRONT] Release
  apps/server/src/typegoose/Traductions.test.ts
  apps/server/src/typegoose/Traductions.ts
  migrations/1733826190794_RemoveStuckedToReview.ts
Labels: release

#2523 [STG-MOBILE] Release
  apps/server/src/typegoose/Traductions.test.ts
  apps/server/src/typegoose/Traductions.ts
  migrations/1733826190794_RemoveStuckedToReview.ts
Labels: release
