Repository refugies-info/karfur, pull requests merged in 2024-07, with the labels that each got.

#2172 [STG-BACK] Release
  .circleci/config.yml
  .vscode/launch.json
  .vscode/settings.json
  api-types/package-lock.json
  api-types/package.json
  client/Dockerfile
  client/jest/setup.js
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/src/__tests__/__snapshots__/index.test.tsx.snap
  client/src/__tests__/__snapshots__/recherche.test.tsx.snap
  client/src/components/Pages/dispositif/Edition/MapEdit/MapEdit.tsx
  client/src/components/Pages/dispositif/Map/Map.tsx
  client/src/components/UI/EVAIcon/EVAIcon.tsx
  client/src/components/UI/FButton/FButton.tsx
  client/src/services/User/__tests__/user.saga.test.ts
  client/src/services/User/user.saga.ts
  documentation/README.md
  documentation/api-types/README.md
  documentation/client/README.md
  documentation/server/README.md
  package-lock.json
  package.json
  server/Dockerfile
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/src/modules/langues/langues.service.ts
  server/src/modules/mail/mail.service.ts
  server/src/modules/mail/mailFunctions.ts
  server/src/modules/mail/sendMailWhenDispositifPublished.ts
  server/src/modules/users/__tests__/user.service.test.ts
  server/src/workflows/dispositif/updateDispositif/updateDispositif.test.ts
  server/src/workflows/mail/sendDraftReminderMail/sendDraftReminderMail.ts
  server/src/workflows/themes/postThemes/postThemes.ts
  server/src/workflows/translation/translate/translate.ts
  server/src/workflows/users/register/register.test.ts
  server/tsconfig.json
  yarn.lock
Labels: release

#2171 [STG-FRONT] Release
  .circleci/config.yml
  .vscode/launch.json
  .vscode/settings.json
  api-types/package-lock.json
  api-types/package.json
  client/Dockerfile
  client/jest/setup.js
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/src/__tests__/__snapshots__/index.test.tsx.snap
  client/src/__tests__/__snapshots__/recherche.test.tsx.snap
  client/src/components/Pages/dispositif/Edition/MapEdit/MapEdit.tsx
  client/src/components/Pages/dispositif/Map/Map.tsx
  client/src/components/UI/EVAIcon/EVAIcon.tsx
  client/src/components/UI/FButton/FButton.tsx
  client/src/services/User/__tests__/user.saga.test.ts
  client/src/services/User/user.saga.ts
  documentation/README.md
  documentation/api-types/README.md
  documentation/client/README.md
  documentation/server/README.md
  package-lock.json
  package.json
  server/Dockerfile
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/src/modules/langues/langues.service.ts
  server/src/modules/mail/mail.service.ts
  server/src/modules/mail/mailFunctions.ts
  server/src/modules/mail/sendMailWhenDispositifPublished.ts
  server/src/modules/users/__tests__/user.service.test.ts
  server/src/workflows/dispositif/updateDispositif/updateDispositif.test.ts
  server/src/workflows/mail/sendDraftReminderMail/sendDraftReminderMail.ts
  server/src/workflows/themes/postThemes/postThemes.ts
  server/src/workflows/translation/translate/translate.ts
  server/src/workflows/users/register/register.test.ts
  server/tsconfig.json
  yarn.lock
Labels: release

#2176 [PROD-FRONT] Release
  .circleci/config.yml
  .vscode/launch.json
  .vscode/settings.json
  api-types/package-lock.json
  api-types/package.json
  client/Dockerfile
  client/jest/setup.js
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/src/__tests__/__snapshots__/index.test.tsx.snap
  client/src/__tests__/__snapshots__/recherche.test.tsx.snap
  client/src/components/Pages/dispositif/Edition/MapEdit/MapEdit.tsx
  client/src/components/Pages/dispositif/Map/Map.tsx
  client/src/components/UI/EVAIcon/EVAIcon.tsx
  client/src/components/UI/FButton/FButton.tsx
  client/src/services/User/__tests__/user.saga.test.ts
  client/src/services/User/user.saga.ts
  documentation/README.md
  documentation/api-types/README.md
  documentation/client/README.md
  documentation/server/README.md
  package-lock.json
  package.json
  server/Dockerfile
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/src/modules/langues/langues.service.ts
  server/src/modules/mail/mail.service.ts
  server/src/modules/mail/mailFunctions.ts
  server/src/modules/mail/sendMailWhenDispositifPublished.ts
  server/src/modules/users/__tests__/user.service.test.ts
  server/src/workflows/dispositif/updateDispositif/updateDispositif.test.ts
  server/src/workflows/mail/sendDraftReminderMail/sendDraftReminderMail.ts
  server/src/workflows/themes/postThemes/postThemes.ts
  server/src/workflows/translation/translate/translate.ts
  server/src/workflows/users/register/register.test.ts
  server/tsconfig.json
  yarn.lock
Labels: release

#2182 [STG-FRONT] Release
  server/package.json
  yarn.lock
Labels: release

#2181 [STG-BACK] Release
  server/package.json
  yarn.lock
Labels: release

#2184 [STG-BACK] Release
  .dockerignore
  client/Dockerfile
  client/src/lib/tracking.ts
  package.json
  server/Dockerfile
Labels: release

#2185 [STG-FRONT] Release
  .dockerignore
  client/Dockerfile
  client/src/lib/tracking.ts
  package.json
  server/Dockerfile
Labels: release

#2187 [STG-BACK] Release
  client/Dockerfile
Labels: release

#2188 [STG-FRONT] Release
  client/Dockerfile
Labels: release

#2192 [STG-BACK] Release
  client/src/scss/_variables.scss
Labels: release

#2191 [STG-FRONT] Release
  client/src/scss/_variables.scss
Labels: release

#2197 [STG-BACK] Release
  server/package.json
Labels: release

#2199 [STG-BACK] Release
  package.json
Labels: release

#2195 [STG-FRONT] Release
  package.json
  server/Dockerfile
  server/package.json
Labels: release

#2201 [PROD-BACK] Release
  .dockerignore
  client/Dockerfile
  client/src/lib/tracking.ts
  client/src/scss/_variables.scss
  package.json
  server/Dockerfile
  server/package.json
  yarn.lock
Labels: release

#2200 [PROD-FRONT] Release
  .dockerignore
  client/Dockerfile
  client/src/lib/tracking.ts
  client/src/scss/_variables.scss
  package.json
  server/Dockerfile
  server/package.json
  yarn.lock
Labels: release

#2189 feat(client): :sparkles: new sticky searchbar design
  .vscode/launch.json
  client/src/__fixtures__/reduxStore.ts
  client/src/__tests__/__snapshots__/recherche.test.tsx.snap
  client/src/__tests__/recherche.test.tsx
  client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.desktop.tsx
  client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.mobile.tsx
  client/src/components/Pages/recherche/SearchHeader/Filter/DropdownButton/DropdownButton.module.scss
  client/src/components/Pages/recherche/SearchHeader/Filter/DropdownButton/DropdownButton.tsx
  client/src/components/Pages/recherche/SearchHeader/Filter/DropdownButton/index.ts
  client/src/components/Pages/recherche/SearchHeader/Filter/Filter.module.scss
  client/src/components/Pages/recherche/SearchHeader/Filter/Filter.tsx
  client/src/components/Pages/recherche/SearchHeader/Filter/index.ts
  client/src/components/Pages/recherche/SearchHeader/Filters.module.scss
  client/src/components/Pages/recherche/SearchHeader/Filters.tsx
  client/src/components/Pages/recherche/SearchHeader/SearchHeader.desktop.module.scss
  client/src/components/Pages/recherche/SearchHeader/SearchHeader.desktop.tsx
  client/src/components/Pages/recherche/SearchHeader/SearchHeader.mobile.module.scss
  client/src/components/Pages/recherche/SearchHeader/SearchHeader.mobile.tsx
  client/src/components/Pages/recherche/SearchHeader/SearchHeader.module.scss
  client/src/components/Pages/recherche/SearchHeader/SearchHeader.tsx
  client/src/components/Pages/recherche/SecondaryFilter/SecondaryFilter.desktop.tsx
  client/src/components/Pages/recherche/SecondaryFilter/SecondaryFilter.mobile.tsx
  client/src/components/Pages/recherche/SecondaryFilter/SecondaryFilter.tsx
  client/src/components/Pages/recherche/SecondaryFilter/index.ts
  client/src/data/searchFilters.ts
  client/src/lib/recherche/decodeUrlQuery/decodeUrlQuery.ts
  client/src/locales/fr/common.json
  client/src/pages/recherche.tsx
  client/src/services/SearchResults/searchResults.actions.ts
  client/src/services/SearchResults/searchResults.reducer.ts
  client/src/services/SearchResults/searchResults.selector.ts
Labels: enhancement

#2202 feat: big search bar
  .vscode/settings.json
  client/src/__tests__/__snapshots__/recherche.test.tsx.snap
  client/src/components/Pages/recherche/SearchHeader/Filters.module.scss
  client/src/components/Pages/recherche/SearchHeader/Filters.tsx
  client/src/components/Pages/recherche/SearchHeader/SearchHeader.module.scss
  client/src/components/Pages/recherche/SearchHeader/SearchHeader.tsx
  client/src/locales/fr/common.json
  client/src/pages/recherche.tsx
Labels: enhancement

#2215 build(client): :wrench: fix vscode very slow when checking types or autocomplete
  client/package.json
  client/tsconfig.json
  yarn.lock
Labels: dependencies

#2178 feat: update agir page
  client/src/__tests__/__snapshots__/agir.test.tsx.snap
  client/src/components/UI/MapFrance/MapFrance.module.scss
  client/src/components/UI/MapFrance/MapFrance.tsx
  client/src/components/UI/Tooltip/Tooltip.tsx
  client/src/data/agirOperators.ts
  client/src/pages/agir.tsx
  client/src/scss/pages/agir.module.scss
Labels: enhancement
