Repository refugies-info/karfur, pull requests merged in 2024-10, with the labels that each got.

#2304 [STG-BACK] Release
  apps/client/package.json
  apps/client/src/components/Content/DispositifTranslate/DispositifTranslate.tsx
  apps/client/src/components/Pages/dispositif/Edition/AccordionsEdit/AccordionItem/AccordionItem.tsx
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/PublishModal/MissingContent/MissingContent.tsx
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/PublishModal/MissingContent/data.ts
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/functions.ts
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/MissingSteps/data.ts
  apps/client/src/components/Pages/dispositif/Edition/LeftSidebarEdition/LeftSidebarEdition.tsx
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/CardDemarcheAdministration.module.scss
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/CardDemarcheAdministration.tsx
  apps/client/src/hooks/dispositif/useDispositifTranslation/progressFunctions.ts
  apps/client/src/hooks/dispositif/useDispositifTranslation/useDispositifTranslation.ts
  apps/client/src/pages/demarche/[id]/translate.tsx
  apps/client/src/pages/dispositif/[id]/translate.tsx
  apps/server/src/controllers/dispositifController.ts
  apps/server/src/modules/dispositif/dispositif.service.ts
  apps/server/src/workflows/dispositif/getContentById/getContentById.ts
  package.json
  packages/api-types/src/modules/translations.ts
  yarn.lock
Labels: release

#2303 [STG-FRONT] Release
  apps/client/package.json
  apps/client/src/components/Content/DispositifTranslate/DispositifTranslate.tsx
  apps/client/src/components/Pages/dispositif/Edition/AccordionsEdit/AccordionItem/AccordionItem.tsx
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/PublishModal/MissingContent/MissingContent.tsx
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/PublishModal/MissingContent/data.ts
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/CustomNavbarEdit/functions.ts
  apps/client/src/components/Pages/dispositif/Edition/CustomNavbar/MissingSteps/data.ts
  apps/client/src/components/Pages/dispositif/Edition/LeftSidebarEdition/LeftSidebarEdition.tsx
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/CardDemarcheAdministration.module.scss
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/CardDemarcheAdministration.tsx
  apps/client/src/hooks/dispositif/useDispositifTranslation/progressFunctions.ts
  apps/client/src/hooks/dispositif/useDispositifTranslation/useDispositifTranslation.ts
  apps/client/src/pages/demarche/[id]/translate.tsx
  apps/client/src/pages/dispositif/[id]/translate.tsx
  apps/server/src/controllers/dispositifController.ts
  apps/server/src/modules/dispositif/dispositif.service.ts
  apps/server/src/workflows/dispositif/getContentById/getContentById.ts
  package.json
  packages/api-types/src/modules/translations.ts
  yarn.lock
Labels: release

#2294 fix tiles (RI-17, RI-37, RI-38)
  apps/client/src/__tests__/__snapshots__/index.test.tsx.snap
  apps/client/src/components/Backend/screens/UserFavorites/UserFavorites.tsx
  apps/client/src/components/Backend/screens/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  apps/client/src/components/Pages/annuaire/id/RightAnnuaireDetails.tsx
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalAbstract/ModalAbstract.tsx
  apps/client/src/components/Pages/recherche/CardSlider/CardSlider.tsx
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.module.scss
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.tsx
  apps/client/src/components/UI/DemarcheCard/DemarcheCard.tsx
  apps/client/src/components/UI/DemarcheCard/index.ts
  apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
  apps/client/src/components/UI/NewThemeBadge/NewThemeBadge.module.scss
  apps/client/src/lib/dispositif/getMetadataText.ts
  apps/client/src/scss/components/contentCard.module.scss
Labels: bug

#2314 Jeremie/ri 107 rr themes dropdown responsive
  apps/client/package.json
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/DropdownButton/DropdownButton.module.scss
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/Filter.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/MenuLayouts/DialogMenuLayout.module.scss
  apps/client/src/components/Pages/recherche/SearchHeader/Filters.tsx
  apps/client/src/components/Pages/recherche/ThemeMenu/AllNeedsItem.module.css
  apps/client/src/components/Pages/recherche/ThemeMenu/AllNeedsItem.tsx
  apps/client/src/components/Pages/recherche/ThemeMenu/Needs.module.css
  apps/client/src/components/Pages/recherche/ThemeMenu/Needs.tsx
  apps/client/src/components/Pages/recherche/ThemeMenu/SearchResults.module.css
  apps/client/src/components/Pages/recherche/ThemeMenu/ThemeItem.mobile.module.scss
  apps/client/src/components/Pages/recherche/ThemeMenu/ThemeItem.mobile.tsx
  apps/client/src/components/Pages/recherche/ThemeMenu/ThemeMenu.module.css
  apps/client/src/components/Pages/recherche/ThemeMenu/ThemeMenu.module.scss
  apps/client/src/components/Pages/recherche/ThemeMenu/ThemeMenu.tsx
  apps/client/src/components/Pages/recherche/ThemeMenu/Themes.module.css
  apps/client/src/components/Pages/recherche/ThemeMenu/Themes.tsx
  apps/client/src/components/UI/SearchButton/SearchButton.module.css
  yarn.lock
Labels: enhancement

#2313 fix(client): :bug: fix relative date for demarche card
  apps/client/src/__tests__/__snapshots__/index.test.tsx.snap
  apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
  apps/client/src/lib/getRelativeDate.test.ts
  apps/client/src/lib/getRelativeDate.ts
  apps/client/src/locales/fr/common.json
Labels: bug

#2319 Matthieu/ri-17-rr-tuiles-global
  apps/client/src/components/Backend/screens/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
Labels: bug

#2320 feat: :sparkles: allow to delete administration
  apps/client/src/components/Pages/dispositif/Edition/LeftSidebarEdition/LeftSidebarEdition.tsx
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalDemarcheAdministration/ModalDemarcheAdministration.tsx
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/CardDemarcheAdministration.module.scss
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/CardDemarcheAdministration.tsx
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/DeleteContentModal/DeleteContentModal.module.scss
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/DeleteContentModal/DeleteContentModal.tsx
  apps/client/src/components/Pages/dispositif/Metadatas/CardDemarcheAdministration/DeleteContentModal/index.ts
  apps/server/src/modules/dispositif/dispositif.service.ts
  apps/server/src/typegoose/Dispositif.ts
  apps/server/src/workflows/dispositif/updateDispositif/updateDispositif.ts
  packages/api-types/src/generics.ts
Labels: enhancement

#2322 Matthieu/ri-90-rr-impact-sur-la-page-daccueil-de-ri
  apps/client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.desktop.module.scss
  apps/client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.desktop.tsx
  apps/client/src/components/Pages/homepage/SearchDropdown/SearchDropdown.tsx
  apps/client/src/components/Pages/recherche/CardSlider/CardSlider.module.scss
  apps/client/src/components/UI/ContentSlider/ContentSlider.module.scss
  apps/client/src/scss/components/contentCard.module.scss
Labels: bug

#2323 feat(client): :sparkles: highlight search result
  apps/client/src/scss/components/contentCard.module.scss
Labels: enhancement

#2321 Sticky search bar responsive fixes + current filters counter
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/DropdownButton/DropdownButton.module.scss
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/DropdownButton/DropdownButton.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/Filter.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/MenuLayouts/DialogMenuLayout.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/MenuLayouts/index.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filters.module.scss
  apps/client/src/components/Pages/recherche/SearchHeader/Filters.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/SearchHeader.module.scss
  apps/client/src/components/Pages/recherche/SearchHeader/SearchHeader.tsx
  apps/client/src/hooks/useIsSticky.ts
  apps/client/src/scss/mixins/_responsive.scss
Labels: enhancement

#2326 feat(client): :sparkles: update search with no result
  apps/client/src/__fixtures__/reduxStore.ts
  apps/client/src/__tests__/__snapshots__/recherche.test.tsx.snap
  apps/client/src/__tests__/recherche.test.tsx
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.module.scss
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.tsx
  apps/client/src/lib/recherche/queryContents.ts
  apps/client/src/locales/ar/common.json
  apps/client/src/locales/en/common.json
  apps/client/src/locales/fa/common.json
  apps/client/src/locales/fr/common.json
  apps/client/src/locales/ps/common.json
  apps/client/src/locales/ru/common.json
  apps/client/src/locales/ti/common.json
  apps/client/src/locales/uk/common.json
  apps/client/src/pages/recherche.tsx
  apps/client/src/services/SearchResults/searchResults.actionTypes.ts
  apps/client/src/services/SearchResults/searchResults.actions.ts
  apps/client/src/services/SearchResults/searchResults.reducer.ts
  apps/client/src/services/SearchResults/searchResults.selector.ts
Labels: enhancement

#2331 feat(client): :chart_with_upwards_trend: update tracking
  apps/client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.desktop.tsx
  apps/client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.mobile.tsx
  apps/client/src/components/Pages/recherche/LocationMenu/LocationMenu.tsx
  apps/client/src/components/Pages/recherche/ResultsFilter/ResultsFilter.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/Filter.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/MenuLayouts/DialogMenuLayout.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filter/MenuLayouts/DropDownMenuLayout.tsx
  apps/client/src/components/Pages/recherche/SearchHeader/Filters.tsx
  apps/client/src/components/Pages/recherche/ThemeMenu/AllNeedsItem.tsx
  apps/client/src/components/Pages/recherche/ThemeMenu/NeedItem.tsx
  apps/client/src/components/Pages/recherche/ThemeMenu/ThemeMenu.tsx
  apps/client/src/hooks/index.ts
  apps/client/src/hooks/useSearchEventName.ts
Labels: enhancement

#2329 Jeremie/ri 33 rr version mobile tuiles
  apps/client/src/__tests__/__snapshots__/index.test.tsx.snap
  apps/client/src/components/Backend/screens/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.module.scss
  apps/client/src/components/Pages/recherche/ThemeMenu/SearchResults.module.css
  apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
  apps/client/src/scss/components/contentCard.module.scss
Labels: enhancement

#2332 fix: various improvements
  apps/client/package.json
  apps/client/src/components/UI/Checkbox/CheckboxIcon.tsx
  apps/client/src/services/SearchResults/searchResults.selector.ts
  apps/client/src/services/User/user.selectors.ts
  apps/client/src/services/UserStructure/userStructure.selectors.ts
  yarn.lock
Labels: bug

#2334 WIP: fix(client): :bug: fix card preview
  apps/client/src/__tests__/__snapshots__/index.test.tsx.snap
  apps/client/src/components/Backend/screens/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalAbstract/ModalAbstract.module.scss
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalAbstract/ModalAbstract.tsx
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalAbstract/functions.ts
  apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
  apps/client/src/lib/getTheme.ts
  apps/client/src/scss/components/contentCard.module.scss
Labels: bug

#2347 Ri 33 rr version mobile tuiles cleanup
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.module.scss
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.tsx
  apps/client/src/scss/components/contentCard.module.scss
Labels: enhancement

#2333 feat(mobile): :sparkles: show administration logo on app
  apps/mobile/jest.setup.js
  apps/mobile/package.json
  apps/mobile/src/components/Content/AccordionHeaderFromHtml.tsx
  apps/mobile/src/components/Content/ContentFromHtml.tsx
  apps/mobile/src/components/Content/ContentImage.tsx
  apps/mobile/src/components/Content/TextFromHtml.tsx
  apps/mobile/src/components/Contents/ContentSummary.tsx
  apps/mobile/src/components/Contents/DemarcheImage.tsx
  apps/mobile/src/screens/ContentScreen/ContentScreen.tsx
  apps/mobile/src/screens/__tests__/__snapshots__/ContentScreen.test.tsx.snap
  apps/mobile/src/utils/API.ts
  apps/server/src/workflows/dispositif/getContentsForApp/getContentsForApp.ts
  package.json
  yarn.lock
Labels: enhancement

#2352 fix(client): :bug: position dropdown
  apps/client/src/components/Pages/homepage/SearchDropdown/SearchDropdown.tsx
Labels: bug

#2349 fix(client): :bug: review demo card in modalAbstract
  apps/client/src/__tests__/__snapshots__/index.test.tsx.snap
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalAbstract/ModalAbstract.module.scss
  apps/client/src/components/Pages/dispositif/Edition/Modals/ModalAbstract/ModalAbstract.tsx
  apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
  apps/client/src/hooks/useCardImage.ts
  apps/client/src/lib/getTheme.ts
  apps/client/src/scss/components/contentCard.module.scss
Labels: bug

#2376 [STG-BACK] Release
  apps/client/src/components/Backend/screens/Admin/AdminUsers/AdminUsers.tsx
  apps/client/src/components/Backend/screens/Admin/AdminUsers/data.ts
  apps/client/src/components/Pages/homepage/SearchDropdown/SearchDropdown.tsx
  apps/server/src/modules/dispositif/dispositif.repository.ts
  apps/server/src/workflows/structure/modifyUserRoleInStructure/modifyUserMembershipInStructure.ts
Labels: release

#2377 [STG-FRONT] Release
  apps/client/src/components/Backend/screens/Admin/AdminUsers/AdminUsers.tsx
  apps/client/src/components/Backend/screens/Admin/AdminUsers/data.ts
  apps/client/src/components/Pages/homepage/SearchDropdown/SearchDropdown.tsx
  apps/server/src/modules/dispositif/dispositif.repository.ts
  apps/server/src/workflows/structure/modifyUserRoleInStructure/modifyUserMembershipInStructure.ts
Labels: release

#2379 Ri 90 Dropdowns scroll bug
  apps/client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.desktop.tsx
  apps/client/src/components/Pages/homepage/SearchDropdown/SearchDropdown.tsx
Labels: bug

#2378 Fix(server): Adapt the getUserContributions dispositif
  apps/server/src/modules/dispositif/dispositif.repository.ts
Labels: enhancement

#2382 [STG-BACK] Release
  .github/workflows/checks.yaml
  apps/client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.desktop.tsx
  apps/client/src/components/Pages/homepage/SearchDropdown/SearchDropdown.tsx
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.module.scss
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.tsx
Labels: release

#2383 [STG-FRONT] Release
  .github/workflows/checks.yaml
  apps/client/src/components/Pages/homepage/HomeSearchHeader/HomeSearchHeader.desktop.tsx
  apps/client/src/components/Pages/homepage/SearchDropdown/SearchDropdown.tsx
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.module.scss
  apps/client/src/components/Pages/recherche/SearchResults/SearchResults.tsx
Labels: release
