Repository refugies-info/karfur, pull requests merged in 2025-01, with the labels that each got.

#2550 Jeremie/ri 484 hd dsfr structure du header 2
  apps/client/src/components/Navigation/Navbar/Navbar.tsx
  apps/client/src/components/UI/LanguageSelector/LanguageItem.module.scss
  apps/client/src/components/UI/LanguageSelector/LanguageItem.tsx
  apps/client/src/hooks/useChangeLanguage.ts
  apps/client/src/locales/fr/common.json
Labels: enhancement

#2551 Jeremie/ri 487 hd dsfr structure des onglets
  apps/client/src/components/Backend/Navigation/useBackendNavigation.ts
  apps/client/src/components/Navigation/Navbar/Navbar.tsx
  apps/client/src/locales/fr/common.json
Labels: enhancement

#2558 Jeremie/ri 511 hd dsfr version mobile
  apps/client/src/components/Navigation/Navbar/Navbar.module.scss
  apps/client/src/components/Navigation/Navbar/Navbar.tsx
  apps/client/src/components/Navigation/Navbar/QuickAccessMenu/LanguageMenu.module.scss
  apps/client/src/components/Navigation/Navbar/QuickAccessMenu/QuickAccessMenu.tsx
  apps/client/src/locales/fr/common.json
Labels: enhancement

#2540 Fix: auth tunnel responsive fixes
  apps/client/src/components/Pages/auth/Layout/Layout.module.scss
  apps/client/src/components/Pages/auth/Layout/Layout.tsx
  apps/client/src/scss/components/auth.module.scss
Labels: bug

#2573 Fix: app download popup background color
  apps/client/src/scss/_bootstrap.scss
Labels: bug

#2581 Jeremie/ri 484 hd dsfr structure du header 3
  apps/client/src/components/Navigation/Navbar/Navbar.module.scss
  apps/client/src/components/Navigation/Navbar/QuickAccessMenu/LanguageMenu.tsx
  apps/client/src/components/UI/DropDown/DropDown.module.scss
  apps/client/src/components/UI/DropDown/DropDown.tsx
  apps/client/src/locales/fr/common.json
  apps/client/src/scss/_dsfr-fix.scss
Labels: enhancement

#2589 [STG-BACK] Release
  .github/workflows/migrate_production.yaml
  apps/client/src/__tests__/__snapshots__/index.test.tsx.snap
  apps/client/src/components/Backend/screens/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  apps/client/src/components/Modals/MobileModal/MobileModal.module.scss
  apps/client/src/components/Navigation/Navbar/Navbar.module.scss
  apps/client/src/components/Navigation/Navbar/QuickAccessMenu/LanguageMenu.tsx
  apps/client/src/components/Pages/dispositif/LangueMenu/LangueMenu.module.scss
  apps/client/src/components/Pages/dispositif/Translation/ModalWelcome/ModalWelcome.module.scss
  apps/client/src/components/Pages/recherche/ThemeMenu/ThemeMenu.module.scss
  apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
  apps/client/src/components/UI/DropDown/DropDown.module.scss
  apps/client/src/components/UI/DropDown/DropDown.tsx
  apps/client/src/locales/fr/common.json
  apps/client/src/scss/_bootstrap.scss
  apps/client/src/scss/_common.scss
  apps/client/src/scss/_dsfr-fix.scss
  apps/client/src/scss/index.css
  apps/client/src/scss/index.scss
  apps/server/package.json
  packages/api-types/package.json
  pnpm-lock.yaml
Labels: release

#2590 [STG-FRONT] Release
  .github/workflows/migrate_production.yaml
  apps/client/src/__tests__/__snapshots__/index.test.tsx.snap
  apps/client/src/components/Backend/screens/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  apps/client/src/components/Modals/MobileModal/MobileModal.module.scss
  apps/client/src/components/Navigation/Navbar/Navbar.module.scss
  apps/client/src/components/Navigation/Navbar/QuickAccessMenu/LanguageMenu.tsx
  apps/client/src/components/Pages/dispositif/LangueMenu/LangueMenu.module.scss
  apps/client/src/components/Pages/dispositif/Translation/ModalWelcome/ModalWelcome.module.scss
  apps/client/src/components/Pages/recherche/ThemeMenu/ThemeMenu.module.scss
  apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
  apps/client/src/components/UI/DropDown/DropDown.module.scss
  apps/client/src/components/UI/DropDown/DropDown.tsx
  apps/client/src/locales/fr/common.json
  apps/client/src/scss/_bootstrap.scss
  apps/client/src/scss/_common.scss
  apps/client/src/scss/_dsfr-fix.scss
  apps/client/src/scss/index.css
  apps/client/src/scss/index.scss
  apps/server/package.json
  packages/api-types/package.json
  pnpm-lock.yaml
Labels: release

#2591 [STG-MOBILE] Release
  .github/workflows/migrate_production.yaml
  apps/client/src/__tests__/__snapshots__/index.test.tsx.snap
  apps/client/src/components/Backend/screens/UserFavorites/__tests__/__snapshots__/UserFavorites.component.test.tsx.snap
  apps/client/src/components/Modals/MobileModal/MobileModal.module.scss
  apps/client/src/components/Navigation/Navbar/Navbar.module.scss
  apps/client/src/components/Navigation/Navbar/QuickAccessMenu/LanguageMenu.tsx
  apps/client/src/components/Pages/dispositif/LangueMenu/LangueMenu.module.scss
  apps/client/src/components/Pages/dispositif/Translation/ModalWelcome/ModalWelcome.module.scss
  apps/client/src/components/Pages/recherche/ThemeMenu/ThemeMenu.module.scss
  apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
  apps/client/src/components/UI/DropDown/DropDown.module.scss
  apps/client/src/components/UI/DropDown/DropDown.tsx
  apps/client/src/locales/fr/common.json
  apps/client/src/scss/_bootstrap.scss
  apps/client/src/scss/_common.scss
  apps/client/src/scss/_dsfr-fix.scss
  apps/client/src/scss/index.css
  apps/client/src/scss/index.scss
  apps/server/package.json
  packages/api-types/package.json
  pnpm-lock.yaml
Labels: release

#2594 [STG-BACK] Release
  apps/server/src/typegoose/Traductions.test.ts
  apps/server/src/typegoose/Traductions.ts
Labels: release
